---
title: "ibama"
author: "Maxwel Coura Oliveira"
date: "4/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
options(scipen=999) 
library(tidyverse)
```

```{r}
sales_class <- readxl::read_excel("Vendas_por_classe_de_uso_2019.xls")
```

```{r}
sales_class1 <- sales_class %>% 
  janitor::row_to_names(row_number = 2) %>% 
  janitor::clean_names() %>% 
  janitor::remove_empty() %>% 
  dplyr::select(-na) %>% 
  drop_na() %>% 
  filter(classe_de_uso != "Total") %>% 
  mutate_at(c(2,3), as.double) %>% 
  mutate(highlight = if_else(classe_de_uso %in% "Herbicida", TRUE, FALSE),
         variable_col = if_else(highlight == TRUE, classe_de_uso, "NA"))
#  mutate_if(is_character, as_factor)
sales_class1
```

```{r}
sales_class2 <- sales_class1 %>% 
  mutate(classe_de_uso = fct_collapse(classe_de_uso,
                                      Outros = c("Protetor de Sementes",
                                                 "Inseticida, Acaricida, Cupinicida, Formicida, Fungicida", "Formicida, Inseticida", "Formicida", "Inseticida, Formicida, Fungicida, Nematicida",
"Moluscicida", "Fungicida, Formicida, Herbicida, Inseticida, Acaricida, Nematicida"))) %>% 
  group_by(classe_de_uso) %>% 
  summarise(qtde_ton_ia = sum(qtde_ton_ia),
            perc_percent = sum(perc_percent)) %>% 
  mutate(classe_de_uso = fct_relevel(classe_de_uso, "Outros")) 
```



```{r}
library(ggtext)
library(extrafont)
library(ggthemes)
library(showtext)
showtext_auto()
font_add_google("Noto Sans JP", "noto_jp")
font_add_google("Aclonica", "aclonica")
```


```{r}
theme_style <- theme(plot.title = element_markdown(hjust = 1,
  family = "aclonica", size = 14),
  plot.subtitle = element_markdown(hjust = 1,
  family = "noto_jp", size = 12),
  plot.caption = element_markdown(hjust = 1,
  family = "aclonica", size = 6),
  legend.position = "none",
  axis.text = element_markdown(family = "noto_jp")
  )


theme_set(theme_test() + theme_style)
```


```{r}
sales_class1 %>% 
  ggplot(aes(x = fct_reorder(classe_de_uso,  qtde_ton_ia), 
             y = qtde_ton_ia, fill = highlight)) +
  geom_col() +
  coord_flip() +
  labs(x = "",
       y = "",
       title = "Vendas por classes de usos dos produtos formulados em 2019",
       subtitle = "Unidade de medida em toneladas de ingrediente ativo",
       caption = "IBAMA 2020 | Figura: @maxwelco") +
  
  ggsave("vendas.pdf")
```



# Ingredientes ativos

```{r warning = FALSE , message = FALSE}
library(readxl)

path <- list.files(path = "ibama_2", pattern = "*.xls", full.names = T) %>% 
  as_tibble() %>% 
  rename(files = value)


data <- path %>% 
  mutate(data = map(files, read_excel)) %>% 
  filter(str_detect(files, "ingredientes")) %>% 
  mutate(year = 2009:2019)
```

  
  
```{r}
clean_data <- function(y){
  
data %>% 
  filter(year == y) %>% 
  unnest(data) %>% 
  janitor::row_to_names(row_number = 2) %>% 
#  mutate(ano = "2012") %>% 
  janitor::clean_names() %>% 
  pivot_longer(cols = ro:df, names_to = "state", values_to = "ton") %>% 
  dplyr::select(ingrediente_ativo, state, ton, vendas_sem_definicao_de_uf,
                vendas_totais) %>% 
  mutate_at(c("ton", "vendas_sem_definicao_de_uf", "vendas_totais"), as.double) %>% 
  mutate_if(is.double, ~round(., 2),
            is_character, as_factor) %>% 
  filter(!is.na(ton))
}

clean_data("2009")
```

```{r}
data1 <- data %>% 
  mutate(clean_dt = map(year, clean_data)) %>% 
  dplyr::select(-files, -data) %>% 
  unnest(clean_dt) %>% 
  mutate(ingrediente_ativo = tolower(ingrediente_ativo)) %>% 
  mutate(ingrediente_ativo = fct_collapse(ingrediente_ativo,
                                          "glifosato" = "glifosato e seus sais"))
```
```{r}
data1 %>% 
  filter(ingrediente_ativo == "glifosato")
```


```{r}
data1 %>% 
  filter(ingrediente_ativo %in% c("atrazina", "2,4-d", "glifosato")) %>% 
  ggplot(aes(x = year, y = vendas_totais, color = ingrediente_ativo)) +
  geom_line() +
  geom_point() +
#  geom_label() +
  scale_x_continuous(
    label = scales::number_format(accuracy = 1)) +
  labs(x = "", y ="",
       title = "Vendas de Ingredientes Ativos por Unidade da Federação",
       subtitle = "Unidade de medida = toneladas de ingrediente ativo (IA)",
       caption = "IBAMA 2020 | Figura: @maxwelco") +
  theme(legend.position = "bottom")
```



# Produção e importação de IA


```{r}
path0 <- "SERIE_2009_2019_Prod_Imp_Exp_Vendas_internas_detalhadas_por_IA.xls"

read_import <- function(year){
  
  readxl::read_excel(path0, sheet = year) %>% 
  janitor::row_to_names(row_number = 2) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(producao_nacional)) %>% 
  dplyr::select(-na) 
  
}
```





```{r}
read_import("2009") %>% 
  bind_rows(read_import("2010")) 
```


```{r}
import <- as.character(2009:2019) %>% 
  as_tibble() %>% 
  rename(year = value)  %>% 
  mutate(data = map(year, read_import)) %>% 
  unnest(data) %>% 
  mutate_at(c("year", "producao_nacional", 
              "importacao", "exportacao", 
              "exportacao", "vendas_internas_totais"), as.double) %>% 
  mutate_at(c("year", "producao_nacional", 
              "importacao", "exportacao", 
              "exportacao", "vendas_internas_totais"), ~ round(., 2)) %>% 
  mutate_if(is.character, as_factor) 
  
import 
```


# Produção e importação de IA - 2019


```{r}
#Ibama - abril 2019
(herb_imp <- read_csv("herbicidas_SIC_2019.xls - RESULTADO_SIC.csv") %>% 
   janitor::row_to_names(row_number = 2) %>% 
   janitor::clean_names() %>% 
   dplyr::select(-na) %>% 
   drop_na() %>% 
   mutate(ingrediente_ativo = as_factor(ingrediente_ativo)) %>% 
   mutate_if(is_character, 
            ~ str_replace(., "\\.", "")) %>% 
   mutate_if(is_character, 
            ~ str_replace_all(., ",", "\\.")) %>% 
   mutate_if(is_character, as.double)
)
```

```{r}
herb_imp %>% 
  pivot_longer(cols = 3:4, names_to = "type", values_to = "value") %>% 
  filter(value != 0) %>% 
  ggplot(aes(x = ingrediente_ativo, y = value, fill = type)) +
  geom_bar(stat = "identity", position = "fill") +
#  facet_grid(~ type) %>% 
  coord_flip() +
  theme(legend.position = "bottom") +
  ggsave("ibama_abril.png")
```






# Histórico agrotóxicos


```{r}
path1 <- "Historico total agrotóxicos_por estado_2000_2018-1.xls"


historico <- readxl::read_excel(path1)
```

```{r}
historico1 <- historico %>% 
  janitor::row_to_names(row_number = 2)  %>% 
  janitor::clean_names() %>% 
  rename(location = na) %>% 
  pivot_longer(cols = qtde:var_percent_15, 
               names_to = "variable", values_to = "value") %>% 
  mutate(year = case_when(
    variable %in% c("qtde", "part_percent") ~ "2000",
    variable %in% c("qtde_2", "part_percent_2", "var_percent") ~ "2001",
    variable %in% c("qtde_3", "part_percent_3", "var_percent_2") ~ "2002",
    variable %in% c("qtde_4", "part_percent_4", "var_percent_3") ~ "2003",
    variable %in% c("qtde_5", "part_percent_5", "var_percent_4") ~ "2004",
    variable %in% c("qtde_6", "part_percent_6", "var_percent_5") ~ "2005",
    variable %in% c("qtde_7", "part_percent_7", "var_percent_6") ~ "2006",
    variable %in% c("qtde_8", "part_percent_8", "var_percent_7") ~ "2009",
    variable %in% c("qtde_9", "part_percent_9", "var_percent_8") ~ "2010",
    variable %in% c("qtde_10", "part_percent_10", "var_percent_9") ~ "2011",
    variable %in% c("qtde_11", "part_percent_11", "var_percent_10") ~ "2012",
    variable %in% c("qtde_12", "part_percent_12", "var_percent_11") ~ "2013",
    variable %in% c("qtde_13", "part_percent_13", "var_percent_12") ~ "2014",
    variable %in% c("qtde_14", "part_percent_14", "var_percent_13") ~ "2015",
    variable %in% c("qtde_15", "part_percent_15", "var_percent_14") ~ "2016",
    variable %in% c("qtde_16", "part_percent_16", "var_percent_15") ~ "2017",
    variable %in% c("qtde_17", "part_percent_17", "var_percent_16") ~ "2018",
    TRUE ~ "NA"))
```


```{r}
historico2 <- historico1 %>% 
mutate(variable = str_remove(variable, "(\\s+[A-Za-z]+)?[0-9-]+")) %>% 
  mutate(variable = fct_recode(variable,
                               "qtde" = "qtde_",
                               "part_percent" = "part_percent_",
                               "var_percent" = "var_percent_")) %>% 
  mutate(value = round(as.double(value), 2),
         year = as.integer(year)) %>% 
  group_by(year, location) %>% 
#  rowid_to_column() %>% 
  pivot_wider(
              names_from = variable,  values_fn = list(count=list),
              values_from = value) %>% 
  unchop(everything())
```

```{r}
historico2 %>% 
  filter(location %in% c("RS", "PR", "SC")) %>% 
  ggplot(aes(x = year, y = qtde, color = location)) +
  geom_line() +
  geom_point() +
  theme(legend.position = "bottom")
```







