---
title: "tabela_uy"
author: "Maxwel Coura Oliveira"
date: "2/14/2022"
output: html_document
---



```{r}
library(tidyverse)
library(ggthemes)
library(ggtext)
library(reactablefmtr)
library(ggbump)
library(waffle)
```

```{r}
read_csv("tabela_uy.csv") |> 
  janitor::clean_names() |> 
  mutate(ing_ativo = str_to_lower(ing_ativo)) |> 
  mutate(volumenes_cif_en_us = volumenes_cif_en_us * 100) -> uy_table
```

```{r}
uy_table |> 
  mutate(volumenes_cif_en_us = round(volumenes_cif_en_us, 0)) |> 
  pivot_wider(names_from = year, values_from = volumenes_cif_en_us) |> 
  dplyr::select(-moa_group) -> uy_table1
```



```{r}
library(tidyverse)
library(ggthemes)
library(lubridate)
library(waffle)
library(ggtext)
```

```{r}
read_csv("tabela_uy.csv") |> 
  janitor::clean_names() -> uy_table
```


```{r}
uy_table |> 
  mutate(values = as.integer(round(values, 0))) |> 
  group_by(year) |> 
  summarise(values = sum(values))
```





```{r}
uy_table |> 
  group_by(year) |> 
#  mutate(volumenes_cif_en_us = round(volumenes_cif_en_us, 0)) |> 
  summarise(values = sum(values))
```


```{r}
mycolors <- c("#333333", "#E69F00", "#56B4E9", "#999999", 
              "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
              RColorBrewer::brewer.pal(name="Set1", n = 5))

uy_table |> 
  mutate(values = as.integer(round(values, 0))) |> 
  mutate(year = as_factor(year)) |> 
  mutate_if(is.character, as_factor) |> 
  group_by(year, moa_group) |> 
  summarise(values = sum(values)) |> 
  ggplot(aes(fill = moa_group, values = values)) +
  geom_waffle(color = "white", size = .25, n_rows = 10, flip = TRUE) +
  facet_wrap(~year, nrow = 1, strip.position = "bottom") +
  scale_x_discrete() + 
  labs(fill = "SOA group",
       y = "% of CIF in US$") +
  scale_y_continuous(
    labels = function(x) x * 10, # make this multiplyer the same as n_rows
                     expand = c(0,0)) +
  scale_fill_manual(values = mycolors) +
  theme_bw() +
  theme(legend.position = "right",
        legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        legend.key.size = unit(1, "lines"),
        legend.title = element_markdown(size = 30, face = "bold", 
                                        lineheight = 0.2),
        legend.text = element_markdown(size = 30),
        axis.title = element_markdown(size = 30),
        plot.caption = element_markdown(size = 20, color = "#333333"),
        axis.text = element_markdown(size = 25),
        strip.text = element_markdown(face = "bold", size = 30))
        legend.background = element_rect(color = NA)

ggsave("uy_fig.png", width = 9, height = 4)
```


```{r}
tribble(
  ~year, ~volume, ~price, ~type,
  1990, 0.380, 5, "A",
  1995, 0.990, 12, "A",
  1996, 1.291, 17, "A",
  1997, 1.646, 21, "A",
  1998, 2.058, 24, "A",
  1999, 2.090, 23, "A",
  2000, 2.080, 18, "A",
  2005, 6.726, 37, "A",
  2007, 10.991, 68, "A",
  2014, 19.058, 155, "A",
  2018, 12.488, 107, "A",
  2020, 10.391, 77, "A"
) -> fig6
```


```{r}
ylim.prim <- c(0, 179)   # in this example, precipitation
ylim.sec <- c(0, 22)    # in this example, temperature
b <- diff(ylim.prim)/diff(ylim.sec)
a <- ylim.prim[1] - b*ylim.sec[1] # there was a bug here
```



```{r}
fig6 |> 
  ggplot(aes(x = factor(year), y = a + volume*b)) +
  geom_bar(stat = "identity", fill = "#E69F00", show.legend = TRUE) +
  labs(x = NULL) +
  scale_y_continuous(
    "Volume (× 1000 ton of active ingredient)", 
        sec.axis = sec_axis(~ (. - a)/b, name = "CIF price (million US$)",
                        breaks = seq(0, 22, 5))) +
  geom_point(aes(x = factor(year), y = price),
             size = 3,
             shape = 23,
             fill = 1) +
  geom_line(aes(x = factor(year), 
                y = price, 
                group = type),
            show.legend = TRUE,
            color = 1) +
  theme_bw(base_family = "lato") +
  annotate("richtext", label = "CIF price",
           size = 10,
           fill = "#E69F00",
           fontface = "bold",
           color = 1,
           x = 7.4, y = 70) +
  annotate("text", label = "Volume",
           fontface = "bold",
           size = 10,
           color = 1,
           x = 4, y = 30) +
  theme(legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        legend.key.size = unit(0.7, "lines"),
        legend.text = element_markdown(size = 22),
        axis.title = element_markdown(size = 30),
        axis.text = element_markdown(size = 25),
        strip.text = element_markdown(face = "bold", size = 26)) -> fig6a

ggsave("fig6.png")
```


```{r}
colors <- c("#78A8D1",  "#EFBF6A", "#AF7366", "#CDD4E4",  "#E7CDC2",
            "#CF9FFF", "#B2AAA2", "#B18147", "#C9BDA3", "#FF9999",
            "#a2e665")
```


```{r}
uy_table %>% 
  filter(moa_group != "Other") |> 
  group_by(year, moa_group) %>% 
  summarise(values = round(mean(values),1)) |> 
  arrange(desc(values)) %>% 
  mutate(rank = row_number()) |> 
  ungroup() -> uy_table1
```

```{r}
uy_table1 |> 
  mutate(moa = case_when(
    moa_group == "9" ~ "EPSPs",
    moa_group == "4" ~ "Auxins",
    moa_group == "2" ~ "ALS",
    moa_group == "5" ~ "PSII",
    moa_group == "1" ~ "ACCase",
    moa_group == "22" ~ "PSI",
    moa_group == "14" ~ "PPO", 
    moa_group == "27" ~ "HPPD", 
    moa_group == "3" ~ "Microtubule", 
    moa_group == "15" ~ "LCFA", 
    moa_group == "13" ~ "DXP", 
    TRUE ~ NA_character_
  )) |> 
  filter(!is.na(moa)) -> uy_table2
```



```{r}
colors <- c("#78A8D1",  "#EFBF6A", "#AF7366", "#CDD4E4",  "#E7CDC2",
            "#C9BDA3", "#FF7F50", "#F33A6A", "#a2e665", "#CF9FFF", 
            "#B2AAA2")

```



```{r}
uy_table2 |> 
  ggplot(aes(x = year, 
             y = rank, 
             color = moa,
             label = moa)) +
  geom_text(data = uy_table2 %>% filter(year == 2020),
            mapping = aes(x = year + 1, label = moa), 
            size = 11, hjust = 0, fontface = "bold") +
  geom_text(data = uy_table2 %>% filter(year == 1995),
            mapping = aes(x = year - 1, label = moa), 
            size = 11, hjust = 1, fontface = "bold") +
  geom_bump(size = 2, smooth = 8) +
  geom_point(size = 8) +
  theme_minimal(base_family = "lato") +
  scale_color_manual(values = colors) +
  geom_text(data = uy_table2,
            mapping = aes(label = values), 
            size = 10, color = "#333333") +
  scale_y_reverse(breaks = seq(0, 18, 1)) +
  scale_x_continuous(limits = c(1991, 2024),
                     breaks = c(1995, 1999, 2005, 2007, 2014, 2018, 2020)) +
  labs(x = NULL, y = NULL) +
  theme(legend.position = "none",
        axis.text.y = element_markdown(size = 30, face = "bold"),
        plot.caption = element_markdown(size = 20, color = "#333333"),
        axis.ticks = element_blank(),
        axis.text.x = element_markdown(size = 30, face = "bold", 
                                       vjust = 0.5, margin = margin(0,0,0,0, 
                                                                    unit = 'cm'))) -> fig6b

ggsave("uy_fig1.png", bg = "#F9F6EE")
```

```{r}
library(patchwork)
fig6a + fig6b +
  plot_layout(widths = c(1.2, 1.8)) +
  plot_annotation(tag_levels = 'A') & 
  theme(plot.tag = element_text(size = 35, hjust = 0, vjust = 0))

ggsave("figure6.png", width = 12, height = 5) 
```




```{r}
readxl::read_excel("Figure6B.xlsx") |> 
  janitor::clean_names() |> 
  mutate(values = round(volume_percent_cif_us * 100, 0)) |> 
  group_by(year, moa_group) %>% 
  summarise(values = round(mean(values),1)) |> 
  arrange(desc(values)) %>% 
  mutate(rank = row_number()) -> uy.table
```

```{r}
colors <- c("#78A8D1",  "#EFBF6A", "#AF7366", "#CDD4E4",  "#E7CDC2",
            "#C9BDA3", "#FF7F50", "#F33A6A", "#a2e665", "#CF9FFF", 
            "#B2AAA2")

```



```{r}
uy.table |> 
  ggplot(aes(x = year, 
             y = rank, 
             color = moa_group,
             label = moa_group)) +
  geom_text(data = uy.table %>% filter(year == 2020),
            mapping = aes(x = year + 1, label = moa_group), 
            size = 11, hjust = 0, fontface = "bold") +
  geom_text(data = uy.table %>% filter(year == 1995),
            mapping = aes(x = year - 1, label = moa_group), 
            size = 11, hjust = 1, fontface = "bold") +
  theme_minimal(base_family = "lato") +
  geom_bump(size = 2, smooth = 8) +
  geom_point(size = 8, show.legend = FALSE) +
  scale_color_manual(values = colors) +
  geom_text(data = uy.table,
            mapping = aes(label = values), 
            size = 10, color = "#333333") +
  scale_y_reverse(breaks = seq(0, 10, 1)) +
  labs(x = NULL, y = NULL) +
  scale_x_continuous(limits = c(1991, 2024),
                     breaks = c(1995, 1999, 2005, 2007, 2014, 2018, 2020)) +
  theme(legend.position = "none",
        axis.text = element_markdown(size = 30, face = "bold"),
        axis.ticks = element_blank())

ggsave("uy_fig2.png", bg = "#F9F6EE")
```


