---
title: "graphical_abstract"
author: "Maxwel Coura Oliveira"
date: "10/27/2021"
output: html_document
---

```{r warning =FALSE}
library(tidyverse)
library(ggtext)
library(maps)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
theme_set(theme_bw())
```
sovereignt
```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```

```{r}
world |> tibble() |> 
  arrange(sovereignt) |> 
  filter(region_wb %in% "Latin America & Caribbean")
```


```{r}
world_points <- st_centroid(world)
world_points <- cbind(world, 
                      st_coordinates(st_centroid(world$geometry)))
#  filter(subregion %in% "South America")
```



```{r}
library(ggrepel)
ggplot(data = world_points) +
  geom_sf() +
  geom_sf(world_points |> 
                    filter(continent == "South America"),
          mapping = aes(fill = sovereignt)) +
  coord_sf(xlim = c(-90, -30), ylim = c(-60, 17), expand = FALSE) +
  theme(panel.background = element_rect(fill = "aliceblue"),
        legend.position = c(0.80, 0.95),
        legend.background = element_rect(fill = NA),
        legend.direction = "horizontal",
        axis.text = element_markdown(size = 12),
        legend.title = element_markdown(face = "bold"),
        legend.key.width = unit(2,"line")) +
  guides(fill = guide_colourbar(title.position="top",
                                title.hjust = 0.5)) -> map1
```


```{r}
map1 +
  geom_text_repel(data= world_points |> 
                    filter(continent == "South America"),
                  aes(x=X, y=Y, label=name),
            size = 6, 
            seed = 165,
            color = "#F9F6EE", 
            fontface = "bold") +
  annotate(geom = "richtext", 
           x = -89.9, 
           y = 15, 
           fill = NA, 
           label.color = NA,
           label = "Herbicide use history and perspectives in South America", 
           fontface = "bold", 
           color = "#333333", 
           size = 5.7, 
           hjust = 0) +
  labs(x = NULL, 
       y = NULL) +
  annotate(geom = "text", 
           x = -40, 
           y = -30, 
           label = "Atlantic ocean", 
           fontface = "italic", 
           color = "blue", 
           size = 4) +
  annotate(geom = "text", 
           x = -80, 
           y = -25, 
           label = "Pacific ocean", 
           fontface = "italic", 
           color = "blue", 
           size = 4) +
  annotation_scale(location = "br", 
                   width_hint = 0.4, 
                   text_cex = 1) + 
  annotation_north_arrow(location = "bl", 
                         which_north = "true",
                         pad_x = unit(0.05, "in"),
                         pad_y = unit(0.05, "in"), 
                         style = north_arrow_nautical) +
  scale_fill_viridis_d(option = "H") -> map2
```


```{r}
map2 +
  annotate(geom = "richtext", x = -58, y = 10, 
           label = "Synthetic herbicides were introduced in <br>the 1940s. Since then, herbicides have <br>become a major tool for vegetation <br>management worldwide.", 
           fill = NA, label.color = NA,
           color = "#333333", size = 4, hjust = 0, lineheight = 0.4) +
  annotate(geom = "richtext", x = -62, y = -45, 
           label = "We have provided an overview about the <br>historical use and the future perspectives of <br>herbicides in **South America**. We focused on <br>herbicide use in row crops of Brazil, <br>Argentina, Uruguay, Paraguay, and Chile.", 
           fill = NA, label.color = NA,
           color = "#333333", size = 4, hjust = 0, lineheight = 0.4) 

ggsave("map.png", width = 7, height = 9)
```