---
title: "figuras"
author: "Maxwel Coura Oliveira"
date: "6/30/2021"
output: html_document
---


<!-- Figura 1A -->

```{r}
library(tidyverse)
library(pdftools)
library(ggthemes)
library(ggtext)
library(ggtext)
```

```{r}
library(extrafont)
library(showtext)
showtext_auto()
font_add_google("Roboto", "roboto") 
```



```{r}
raw_pdf <- pdftools::pdf_text("../sindiveg/vendas_hist.pdf")
```


```{r}
raw_text <- raw_pdf[[1]] %>% 
  str_split("\n") %>% 
  unlist()
```

```{r}
table_trimmed <- raw_text %>% 
  .[13:(length(raw_text)-1)] %>% 
  str_trim()
```


```{r}
all_col_names <- c(
  "year",
  "total",
  "herbicida",
  "fungicida",
  "inseticida",
  "acaricida",
  "outros"
)

tab_names <- fwf_empty(
  table_trimmed,
  col_names = all_col_names
)
```

```{r}
vendas_1 <- table_trimmed %>% 
  read_fwf(
    tab_names
  )


vendas_2 <- raw_pdf[[2]] %>% 
  str_split("\n") %>% 
  unlist() %>% 
  .[1:41] %>% 
  str_trim() %>% 
  str_replace_all("\\s{2,}", "|") %>% 
  read_delim(
    delim = "|", 
    col_names = all_col_names
  ) 
```


```{r}
# vendas no valor de US$ 10000
vendas_1 %>% 
  bind_rows(vendas_2) %>% 
  mutate_if(is_character, ~ str_remove_all(., "\\.")) %>% 
   mutate_if(is.double, ~ str_remove_all(., "\\.")) %>% 
  mutate_if(is_character, as.double) %>% 
  filter(!is.na(year)) -> vendas_3
```




```{r eval = FALSE}
# (×1000)
(
vendas_3 %>% 
  pivot_longer(cols = c(3:6), names_to = "type", values_to = "value")  %>% 
#  dplyr::select(year, total, herbicida) %>% 
  ggplot(aes(x = year, y = value / 1000, color = type)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::dollar_format(prefix = "US$ ", 
                                                    big.mark = ",",
                                                    decimal.mark = ".")) +
  labs(y = "Vendas de herbicidas",
       x = NULL,
       title = "O mercado de herbicidas no Brasil",
       subtitle = "As vendas de herbicidas no Brasil aumentaram significantemente após a introdução da tecnologia Roundup <br>Ready em 2002",
       caption = "Fonte: Sindiveg 2018 | Figura: @maxwelco") +
#  geom_segment(aes(x = 2002, y = 5, 
#                   xend = 2002, yend = 1.5), color = "tomato") +
#  geom_curve(x = 2002.3, y = 8, xend = 2005, yend = 8,
#               arrow = arrow(length = unit(0.07, "inch")), 
#               size = 0.4, curvature = 0.3, color = "tomato") + 
#  annotate("text", x = 2011, y = 1, 
#           label = "Introdução da tecnologia\n Roundup Ready",) +
  theme_fivethirtyeight() +
  theme(plot.title.position = "plot",
        plot.subtitle = element_markdown(size = 10))
)
ggsave("vendas.png")
```


Crop harvest - FAO


```{r}
read_csv("crop_harvest.csv") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(value)) %>% 
  group_by(year) %>% 
  summarise(area = sum(value)) -> area_br
```



# IBGE

```{r eval = FALSE}
readxl::read_excel("area_colhida.xlsx") %>% 
  janitor::row_to_names(row_number = 3) %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  pivot_longer(cols = c("x1974":"x2019"), names_to = "year", values_to = "harvest_ha") %>% 
  rename(location = na) %>% 
  mutate(year = str_remove_all(year, "x")) %>% 
  mutate_at(c("year", "harvest_ha"), as.double)
```







```{r}
vendas_3 %>% 
  left_join(area_br, by = "year") %>% 
  mutate(pesticide = fungicida + inseticida + acaricida) %>% 
  pivot_longer(cols = c(3:6, pesticide), names_to = "type", values_to = "value")  %>%
  mutate(rate_herb = (value * 1000) / area) -> pest_sales
```


```{r eval=FALSE}
pest_sales %>% 
  filter(type != "pesticide") %>% 
ggplot(aes(x = year, y = rate_herb, color = type, 
             fill = type, shape = type)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(limits = c(0, 60)) +
  scale_x_continuous(limits = c(1978, 2020.5), 
                     breaks = seq(1980, 2020, by = 10)) +
  labs(y = expression(paste("Pesticide sales (US$ ha "^"-1",")")),
       x = NULL) +
  scale_color_manual(values = c("grey80", "grey80", "#FE4E00", "grey80")) +
  scale_fill_manual(values = c("grey80", "grey80", "#FE4E00", "grey80")) +
  scale_shape_manual(values = c(1, 1, 16, 1)) +
  annotate("text", x = 1998, y = 33, fontface = "bold",
           label = "Herbicide", color = "#FE4E00") +
  geom_curve(x = 2013, y = 55, 
                   xend = 2011, yend = 57,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = 0.3, color = "grey80") + 
  annotate("text", x = 2008, y = 57, #fontface = NULL,
           label = "Inseticide", size = 3, color = "grey80") +
  geom_curve(x = 2007, y = 18, 
                   xend = 2009, yend = 15,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = 0.3, color = "grey80") + 
  annotate("text", x = 2012, y = 15.5, #fontface = NULL,
           label = "Fungicide", size = 3, color = "grey80") +
  geom_curve(x = 2011, y = 1.5, 
                   xend = 2013, yend = 5,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = -0.3, color = "grey80") + 
  annotate("text", x = 2016, y = 5, #fontface = NULL,
           label = "Acaricide", size = 3, color = "grey80") +
  geom_smooth(method = "loess", alpha = 0.05) +
  theme_bw() +
  theme(plot.title.position = "plot",
        legend.position = "none",
        plot.title = element_markdown(),
        plot.subtitle = element_markdown(size = 10)) -> sales


ggsave("vendas_rate.png")
```



```{r}
theme_set(theme_bw(base_family = "roboto"))
pest_sales %>% 
    filter(type %in% c("herbicida", "pesticide")) %>% 
ggplot(aes(x = year, y = rate_herb, color = type, 
             fill = type, shape = type)) +
  geom_point() +
  geom_line() +
#  scale_y_continuous(limits = c(0, 60)) +
  scale_x_continuous(limits = c(1978, 2020), 
                     breaks = seq(1980, 2020, by = 10)) +
  labs(y = expression(paste("Pesticide sales (US$ ha "^"-1",")")),
       x = NULL) +
  scale_colour_manual(values = c("#FE4E00", "#4B0082")) +
  scale_fill_manual(values = c("#FE4E00", "#4B0082")) +
  scale_shape_manual(values = c(16,1)) +
  annotate("text", x = 2015, y = 34, label = "Herbicide", 
           color = "#FE4E00", fontface = "bold") +
  annotate("text", x = 2004, y = 90, label = "Other pesticides", 
           color = "#4B0082", fontface = "bold") +
  geom_smooth(method = "loess", alpha = 0.2) +
  theme_bw() +
  theme(plot.title.position = "plot",
        legend.position = "none",
        plot.title = element_markdown(),
        plot.subtitle = element_markdown(size = 10)) -> sales


ggsave("vendas_rate1.png")
```






```{r}
read_csv("../fao/herbicide_fao.csv")  %>% 
  dplyr::select(Year, Unit, Value) %>% 
  janitor::clean_names() %>% 
  left_join(area_br, by = "year") %>% 
  mutate(rate = (value * 1000) / area) %>% 
  mutate(type =  "herbicide") -> rate_herbicide
```


<!-- Figura 1B -->


# VENDAS DE AGROTÓXICOS E AFINS NO BRASIL NO PERÍODO DE 2000 A 2018 (Unidade: tonelada de ingrediente ativo)


```{r}
path1 <- "../Ibama/ibama_2/Historico total agrotóxicos_por estado_2000_2018-1.xls"


historico <- readxl::read_excel(path1)
```


```{r}
historico1 <- historico %>% 
  janitor::row_to_names(row_number = 2)  %>% 
  janitor::clean_names() %>% 
  rename(location = na) %>% 
  pivot_longer(cols = qtde:var_percent_15, 
               names_to = "variable", values_to = "value") %>% 
  mutate(year = case_when(
    variable %in% c("qtde", "part_percent") ~ "2000",
    variable %in% c("qtde_2", "part_percent_2", "var_percent") ~ "2001",
    variable %in% c("qtde_3", "part_percent_3", "var_percent_2") ~ "2002",
    variable %in% c("qtde_4", "part_percent_4", "var_percent_3") ~ "2003",
    variable %in% c("qtde_5", "part_percent_5", "var_percent_4") ~ "2004",
    variable %in% c("qtde_6", "part_percent_6", "var_percent_5") ~ "2005",
    variable %in% c("qtde_7", "part_percent_7", "var_percent_6") ~ "2006",
    variable %in% c("qtde_8", "part_percent_8", "var_percent_7") ~ "2009",
    variable %in% c("qtde_9", "part_percent_9", "var_percent_8") ~ "2010",
    variable %in% c("qtde_10", "part_percent_10", "var_percent_9") ~ "2011",
    variable %in% c("qtde_11", "part_percent_11", "var_percent_10") ~ "2012",
    variable %in% c("qtde_12", "part_percent_12", "var_percent_11") ~ "2013",
    variable %in% c("qtde_13", "part_percent_13", "var_percent_12") ~ "2014",
    variable %in% c("qtde_14", "part_percent_14", "var_percent_13") ~ "2015",
    variable %in% c("qtde_15", "part_percent_15", "var_percent_14") ~ "2016",
    variable %in% c("qtde_16", "part_percent_16", "var_percent_15") ~ "2017",
    variable %in% c("qtde_17", "part_percent_17", "var_percent_16") ~ "2018",
    TRUE ~ "NA"))
```


```{r}
historico2 <- historico1 %>% 
mutate(variable = str_remove(variable, "(\\s+[A-Za-z]+)?[0-9-]+")) %>% 
  mutate(variable = fct_recode(variable,
                               "qtde" = "qtde_",
                               "part_percent" = "part_percent_",
                               "var_percent" = "var_percent_")) %>% 
  mutate(value = round(as.double(value), 2),
         year = as.integer(year)) %>% 
  group_by(year, location) %>% 
#  rowid_to_column() %>% 
  pivot_wider(
              names_from = variable,  values_fn = list(count=list),
              values_from = value) %>% 
  unchop(everything())
```


```{r}
historico2 %>% 
  filter(location %in% "Total") %>% 
  left_join(area_br, by = c("year")) %>% 
  dplyr::select(year, qtde, area) %>% 
  rename(value = qtde) %>% 
  mutate(rate = value * 1000 / area) %>%
  mutate(type =  "pesticide") -> rate_pesticide
```


```{r}
rate_herbicide %>% 
  bind_rows(rate_pesticide) %>% 
  dplyr::select(-location, -unit) %>% 
  pivot_wider(id_cols = year, names_from = type, values_from = rate) %>% 
  mutate(other = pesticide - herbicide) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "rate") -> ai_rate
```


```{r eval=FALSE}
ai_rate %>% 
  filter(type != "other") %>% 
  filter(!is.na(rate)) %>% 
  ggplot(aes(x = year, y = rate, color = type, 
             fill = type, shape = type)) +
  geom_point() +
  geom_line() +
  geom_smooth(method = "loess", alpha = 0.2) +
  scale_x_continuous(limits = c(1990, 2020), #expand = c(.01, .01),
                     breaks = seq(1990, 2020, by = 5)) +
  scale_y_continuous(limits = c(0, 8), breaks = seq(0, 8, by = 2)) +
  scale_colour_manual(values = c("#FE4E00", "#4B0082")) +
  scale_fill_manual(values = c("#FE4E00", "#4B0082")) +
  scale_shape_manual(values = c(16,1)) +
  annotate("text", x = 2015, y = 2.4, label = "Herbicide", 
           color = "#FE4E00", fontface = "bold") +
  annotate("text", x = 2015, y = 7.6, label = "Pesticide", 
           color = "#4B0082", fontface = "bold") +
  theme_bw() +
  labs(y = expression(paste("Pesticide use (kg ai ha "^"-1",")")),
       x = NULL, color = NULL, fill = NULL) +
  theme(legend.position = "none") -> herb

ggsave("rate.png")
```

```{r}
theme_set(theme_bw(base_family = "roboto"))
ai_rate %>% 
  filter(type != "pesticide") %>% 
  filter(!is.na(rate)) %>% 
  ggplot(aes(x = year, y = rate, color = type, 
             fill = type, shape = type)) +
  geom_point() +
  geom_line() +
  geom_smooth(method = "loess", alpha = 0.2) +
  scale_x_continuous(limits = c(1990, 2020), #expand = c(.01, .01),
                     breaks = seq(1990, 2020, by = 5)) +
  scale_y_continuous(limits = c(0, 5), breaks = seq(0, 5, by = 1)) +
  scale_colour_manual(values = c("#FE4E00", "#4B0082")) +
  scale_fill_manual(values = c("#FE4E00", "#4B0082")) +
  scale_shape_manual(values = c(16,1)) +
  annotate("text", x = 2015, y = 2.5, label = "Herbicide", 
           color = "#FE4E00", fontface = "bold") +
  annotate("text", x = 2015, y = 4.6, label = "Other pesticides", 
           color = "#4B0082", fontface = "bold") +
  annotate("text", x = 2010, y = 0.1, 
           label = "Other pesticides: fungicide, insecticide and acaricide", 
           color = "#4B0082", size = 3) +
  labs(y = expression(paste("Pesticide sales (kg ai ha "^"-1",")")),
       x = NULL, color = NULL, fill = NULL) +
  theme(legend.position = "none") -> herb

ggsave("rate1.png")
```




```{r}
library(patchwork)
sales | herb

ggsave("figure/Figure 1.png", width = 10, height = 5)
```






```{r}
read_csv("../fao/herbicide_fao.csv")  %>% 
  janitor::clean_names() %>% 
  left_join(area_br, by = "year") %>%
  mutate(rate_herb = (value * 1000) / area) %>% 
  ggplot(aes(x = year, y = rate_herb)) +
#  geom_smooth(method = "lm") +
  geom_point() +
  geom_line() +
  labs(title = "Herbicide use per area in Brazil",
       y = "Rate (kg / ha)", 
       caption = "Source: FAO")
```


<!-- Figura 1C -->


```{r eval=FALSE}
read_csv("br_population.csv") %>% 
  filter(Element %in% c("Rural population", "Urban population", 
                        "Total Population - Both sexes")) %>% 
  mutate(Element = str_remove_all(Element, " population")) %>% 
  ggplot(aes(x = Year, y = Value, color = Element)) +
  geom_point(alpha = 0.2) +
  geom_line() +
  theme_classic() +
  labs(y = "Population (x1000)")
```









```{r}
historico2 %>% 
  filter(location %in% "Total") %>% 
  left_join(area_br, by = c("year")) %>% 
  mutate(rate = (qtde * 1000)/area) %>% 
#  drop_na() %>% 
#  filter(!location %in% c("NORTE", "CENTRO-OESTE", "NORDESTE", 
#                          "SUDESTE", "SUL", "BRASIL",
#                          "Total", "SEM DEFINIÇÃO")) %>% 
#  mutate(highlight = if_else(location %in% c("MT", "PR", "RS", "SP"), TRUE, FALSE),
#         variable = if_else(highlight == TRUE, location, "NA")) %>% 
  ggplot(aes(x = year, y = rate)) +
  geom_line() +
  geom_point() +
#  geom_label() + 
#  scale_color_manual(values = c("red", "gray80",  "blue", "darkgreen", "black")) +
  scale_x_continuous(
    label = scales::number_format(accuracy = 1)) +
  labs(x = "", y ="",
       title = "Vendas de ingredientes ativo de pesticidas por area",
       subtitle = "Unidade de medida em kg de ingrediente ativo por ha",
       caption = "IBAMA 2020 | Figura: @maxwelco") +
  theme_hc() 

ggsave("fig.png")
```


<!-- Figura 2 - Aldo -->

```{r}
readxl::read_excel("dados_aldo_2019.xlsx") %>% 
  dplyr::select(15:27) %>% 
  janitor::row_to_names(row_number = 1) %>%
  janitor::clean_names() %>% 
  filter(na != "Ton ia") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  pivot_longer(cols = c(1:10), names_to = "year", values_to = "perc") %>% 
#  rename(ton_ia_2010 = `2010`) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(area_tratada_em_2019)) %>% 
  mutate(ingrediente_ativo = as_factor(ingrediente_ativo)) %>% 
  mutate_if(is_character, as.double) %>%
  filter(!is.na(ingrediente_ativo)) %>% 
  mutate(area_tratada_em_2019 = area_tratada_em_2019 / 1000) %>% 
  mutate_if(is.double, ~round(.,1)) -> perc_increase
```


```{r}
theme_set(theme_bw(base_family = "roboto"))
perc_increase %>% 
  filter(!is.na(perc)) %>% 
  ggplot(aes(x = year, y = perc, color = perc)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
#  geom_point(data = perc_increase %>% 
#               filter(year %in% 2019), mapping = aes(size = area_tratada_em_2019)) +
  scale_x_continuous(limits = c(2010, 2019), breaks = seq(2010, 2019, by = 3)) +
  facet_wrap(~ ingrediente_ativo, scales = "free", ncol = 4) +
  scale_color_viridis_c(option = "H",
                        limits = c(-85, 2300)) +
  labs(y = "% active ingrediente increase since 2009",
       x = NULL, color = NULL) +
  theme(legend.position = c(0.75, 0.05),
        legend.direction = "horizontal",
        legend.key.height = unit(1,"line"),
        legend.key.width = unit(3,"line"),
        legend.title = element_markdown(),
        plot.title.position = "plot",
        strip.text = element_markdown(face="bold"))

ggsave("figure/Figure 2.png", height = 12, width = 9)
```



<!-- Figura 3 -->

Vendas de ing ativo por regiao


```{r warning = FALSE , message = FALSE}
library(readxl)

path <- list.files(path = "../Ibama/ibama_2", pattern = "*.xls", full.names = T) %>% 
  as_tibble() %>% 
  rename(files = value)


data <- path %>% 
  mutate(data = map(files, read_excel)) %>% 
  filter(str_detect(files, "ingredientes")) %>% 
  mutate(year = 2009:2019)



clean_data <- function(y){
  
data %>% 
  filter(year == y) %>% 
  unnest(data) %>% 
  janitor::row_to_names(row_number = 2) %>% 
#  mutate(ano = "2012") %>% 
  janitor::clean_names() %>% 
  pivot_longer(cols = ro:df, names_to = "state", values_to = "ton") %>% 
  dplyr::select(ingrediente_ativo, state, ton, vendas_sem_definicao_de_uf,
                vendas_totais) %>% 
  mutate_at(c("ton", "vendas_sem_definicao_de_uf", "vendas_totais"), as.double) %>% 
  mutate_if(is.double, ~round(., 2),
            is_character, as_factor) %>% 
  filter(!is.na(ton))
}

clean_data("2009")



data1 <- data %>% 
  mutate(clean_dt = map(year, clean_data)) %>% 
  dplyr::select(-files, -data) %>% 
  unnest(clean_dt) %>% 
  mutate(ingrediente_ativo = tolower(ingrediente_ativo)) %>% 
  mutate(ingrediente_ativo = fct_collapse(ingrediente_ativo,
                                          "glifosato" = "glifosato e seus sais"))
```



<!-- Figura 3 - Spark -->


```{r}
(readxl::read_excel("spark_1.xlsx", sheet = "spark_1") %>% 
  mutate(perc = perc / 100,
         total_ha_soa = total_ha * perc) %>% 
#  group_by(season) %>% 
  distinct(total_ha) -> total_ha)
```


```{r}
readxl::read_excel("spark_1.xlsx", sheet = "spark_1") %>% 
  mutate(perc = perc / 100,
         total_ha_soa = total_ha * perc) %>% 
  mutate(herbicide = str_replace_all(herbicide, "Ohters", "Others")) %>% 
  mutate(mi_ha = round(total_ha / 1000000,1)) %>% 
  mutate(mi_ha = str_glue("{mi_ha} mi ha")) %>% 
  mutate(herbicide = case_when(
    perc == "0.074" & year == "2015" ~ "FSI",
    TRUE ~ herbicide 
  )) -> soa_total
```


```{r}
theme_set(theme_bw(base_family = "roboto"))
soa_total %>% 
  ggplot(aes(x = fct_reorder(herbicide, perc), y = perc, 
             label = perc, fill = herbicide)) +
  geom_bar(stat = "identity") +
  scale_fill_viridis_d(option = "H") +
  coord_flip() +
  facet_grid(~ season) +
#  geom_text() +
#  geom_text(soa_total %>% filter(herbicide == "EPSPs"), 
#            mapping = aes(label = mi_ha), y = 0.5, color = "gray30") +
  labs(x = NULL,
       y = NULL,
       fill = NULL) +
  theme(legend.position = "none")


ggsave("figure/soa_use.png")
```


```{r}
theme_set(theme_bw(base_family = "roboto"))

soa_total %>% 
  mutate(herbicide = fct_relevel(herbicide,
                                 levels = c("Others", "Glutamina", 
                                            "DPX", "HPPD", "PPO",
                                            "FSI", "ACCase", "ALS",
                                            "FSII", "Auxinas", "EPSPs"))) %>% 
  mutate(percent = scales::percent(perc, accuracy = .1, trim = FALSE)) %>% 
  ggplot(aes(x = season, y = herbicide, 
             label = percent, fill = perc)) +
  geom_tile() +
  scale_fill_viridis_b(option = "C") +
#  coord_flip() +
#  facet_grid(~ season) +
   geom_text(color = "gray1") +
#  geom_text(soa_total %>% filter(herbicide == "EPSPs"), 
#            mapping = aes(label = mi_ha), y = 0.5, color = "gray30") +
  labs(x = NULL,
       y = NULL,
       fill = NULL) +
  theme(legend.position = "none")


ggsave("figure/soa_use.png", width = 5)
```


```{r}
library(ggbump)
library(cowplot)
library(fishualize)
```

```{r}
soa_total %>% 
  group_by(year) %>% 
  arrange(desc(total_ha_soa)) %>% 
  mutate(rank = row_number()) -> soa_total1

soa_total1 %>% 
  ggplot(aes(x = year, y = rank, color = herbicide,
             label = herbicide)) +
  geom_text(data = soa_total1 %>% filter(year == 2020),
            mapping = aes(x = year + .3, label = herbicide), 
            size = 5, hjust = 0) +
  geom_text(data = soa_total1 %>% filter(year == 2015),
            mapping = aes(x = year - 1.45, label = herbicide), 
            size = 5, hjust = 0) +
  geom_point(size = 7) +
  geom_bump(size = 2, smooth = 8) +
  geom_text(data = soa_total1,
            mapping = aes(label = perc*100), 
            size = 3, color = 1) +
  scale_x_continuous(limits = c(2013.55, 2021.5),
                     breaks = seq(2015, 2020, 1)) +
  theme_minimal_grid(font_size = 14, line_size = 0) +
  scale_y_reverse(breaks = seq(0, 12, 1)) +
#  scale_colour_viridis_d(option = "F") +
  scale_fill_fish_d(option = "Scarus_quoyi") +
  labs(x = NULL) +
  theme(legend.position = "none")

ggsave("figure/soa_use1.png", bg = "beige")
```




```{r}
readxl::read_excel("spark_1.xlsx", sheet = "spark_2") %>% 
  mutate(perc = perc / 100,
         total_ha_soa = total_ha * perc) %>% 
  mutate(crop = str_to_title(crop)) %>% 
  mutate(mi_ha = round(total_ha_soa / 1000000, 5),
         mi_ha = str_glue("{mi_ha} mi ha")) -> soa_crop
```


```{r}
soa_crop %>% 
  ggplot(aes(x = year_season, y = perc, fill = soa)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_grid(~ crop) +
  labs(x = NULL,
       y = NULL,
       fill = NULL) +
  scale_fill_viridis_d(option = "H") +
  geom_text(soa_crop %>% filter(soa == "EPSPs"),
            mapping = aes(label = mi_ha), y = 0.5, 
            angle = 90, color = "gray75") +
  theme_hc()

ggsave("figure/soa_crop.png")
```

```{r}
options(scipen=999)
soa_crop %>%  
  filter(crop == "Soybean") %>% 
  ggplot(aes(x = year, y = total_ha_soa, fill = soa)) +
  geom_area(position = "fill") +
  facet_grid(~ crop) +
#  coord_flip() +
  labs(x = NULL,
       y = NULL,
       fill = NULL) +
  scale_fill_viridis_d(option = "H", guide = guide_legend(nrow = 2)) +
  scale_x_continuous(breaks = c(2018, 2019, 2020)) +
  theme_hc() +
  theme(axis.text = element_markdown(angle = 0))

ggsave("figure/soa_crop1.png", width = 4, height = 4)
```




```{r}
soa_crop %>% 
  filter(crop == "Corn")
```

