---
title: "resistance"
author: "Maxwel Coura Oliveira"
date: "7/15/2021"
output: html_document
---

```{r}
library(rvest)
library(tidyverse)
```

```{r}
country_function <- function(id) {
  
  url <- paste0("http://weedscience.org/Summary/Country.aspx?CountryID=",id,"")
  #id will change by each country id number
  
  # Read url
  resistance <- read_html(url)
  
  # Extract herbicide resistance data
  chart <- resistance %>% 
    html_node(".rgMasterTable") %>% # selector
    html_table(fill = TRUE) # get the table

  # Tidy dataset
  final_chart <- chart %>% 
    janitor::row_to_names(row_number = 2) %>% # make second column header
    janitor::clean_names() %>% # clean header
    as_tibble() %>% # tibble is better than data.frame
    drop_na() %>% # drop NA values
    mutate_at(c("number", "first_year", 
                "country_id", "resist_id"), 
              as.integer) # make columns numbers as integer 
  # Get final dataset
  final_chart 
}
```



```{r}
country <- tribble(
~country_name, ~id,
"argentina", 48,
"australia", 1,
"austria", 2,
"belgium ", 3,
"bolivia", 4,
"brazil", 5,
"bulgaria", 6,
"canada", 7,
"chile", 8,
"china", 9,
"colombia", 10,
"costa rica", 11,
"czech republic", 12,
"denmark", 13,
"ecuador", 14,
"egypt", 15,
"fiji", 16,
"france", 17,
"germany", 18,
"greece", 19,
"hungary", 20,
"india", 21,
"indonesia", 22,
"israel", 23,
"italy", 24,
"japan", 25,
"kenya", 26,
"south korea", 27,
"malaysia", 28,
"mexico", 29,
"new zealand", 30,
"norway", 31,
"philippines", 32,
"poland", 33,
"portugal", 34,
"saudi arabia", 35,
"slovenia", 36,
"south africa", 37,
"spain", 38,
"sri lanka", 39,
"sweden", 40,
"switzerland", 41,
"taiwan", 42,
"netherlands", 43,
"united kingdom", 44,
"united states", 45,
"paraguay", 46,
"thailand", 47,
"cyprus", 53,
"jordan", 55,
"nicaragua", 60,
"russia", 65,
"syria", 69,
"turkey", 71,
"uruguay", 73,
"ethiopia", 76,
"tunisia", 78,
"iran", 79,
"venezuela", 80,
"ireland", 81,
"panama", 82,
"el salvador", 83,
"guatemala", 84,
"honduras", 85,
"pakistan", 86,
"finland", 139,
"kazakhstan", 157,
"latvia", 174,
"lithuania", 185,
"serbia", 245,
"ukraine", 230
)

country
```


```{r}
resistance_data <- country %>% 
  arrange(country_name) %>% #arrange country in alphabetical order
  mutate(resistance_data = map(id, country_function)) # iterate function over id

final_resistance_data <- resistance_data %>% 
  unnest(resistance_data) %>% # unlist resistance data
  dplyr::select(-x)
```

  ggplot(aes(x = first_year, y = n, color = country)) +
  geom_line() +
  geom_point() +
  scale_color_viridis_d(option = "H")
```{r}
final_resistance_data %>% 
  filter(country_name %in% c("argentina", "brazil",
                             "uruguay", "chile", "paraguay",
                             "colombia", "bolivia", "peru",
                             "ecuador", "venezuela")) %>% 
  dplyr::select(-country_name, -id) %>% 
  count(country, first_year) %>% 
  group_by(country) %>% 
  mutate(cum = cumsum(n)) %>% 
  ggplot(aes(x = first_year, y = cum, color = country)) +
  geom_line() +
  geom_point() +
  scale_color_viridis_d(option = "H")
```

```{r warning =FALSE}
library(tidyverse)
library(maps)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
theme_set(theme_bw())
```
```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```

```{r}
tibble(
  country = "Peru",
  n = 0) -> peru

final_resistance_data %>% 
  filter(country_name %in% c("argentina", "brazil",
                             "uruguay", "chile", "paraguay",
                             "colombia", "bolivia", "peru",
                             "ecuador", "venezuela")) %>% 
  dplyr::select(-country_name, -id) %>% 
  count(country) %>% 
  bind_rows(peru) %>% 
  arrange(desc(n)) -> sa_wr
```

```{r}

```


```{r}
world %>% 
#  filter(sovereignt %in% c("Argentina", "Brazil", "Suriname",
#                           "Guyana", "Kiribati",
#                             "Uruguay", "Chile", "Paraguay",
#                             "Colombia", "Bolivia", "Peru",
#                             "Ecuador", "Venezuela")) %>% 
  left_join(sa_wr, by = c("sovereignt" = "country")) -> dt

world_points <- st_centroid(world)
world_points <- cbind(world, 
                      st_coordinates(st_centroid(world$geometry))) %>% 
  filter(sovereignt %in% c("Argentina", "Brazil",
                             "Uruguay", "Chile", "Paraguay",
                             "Colombia", "Bolivia", "Peru",
                             "Ecuador", "Venezuela")) 
```

```{r}
library(extrafont)
library(ggtext)
library(showtext)
showtext_auto()
font_add_google("Roboto", "roboto") 
```




```{r}
theme_set(theme_bw(base_family = "roboto"))
library(ggrepel)
ggplot(data = dt) +
  geom_sf() +
  geom_sf(aes(fill = n)) +
  coord_sf(xlim = c(-90, -30), ylim = c(-60, 17), expand = FALSE) +
  theme(panel.background = element_rect(fill = "aliceblue"),
        legend.position = c(0.80, 0.95),
        legend.background = element_rect(fill = NA),
        legend.direction = "horizontal",
        legend.title = element_markdown(face = "bold"),
        legend.key.width = unit(2,"line")) +
  guides(fill = guide_colourbar(title.position="top",
                                title.hjust = 0.5)) -> map1
```


```{r}
map1 +
  geom_text_repel(data= world_points,aes(x=X, y=Y, label=name),
            size = 4.5, fill = "white", seed = 165,
            color = "white", fontface = "bold", 
            check_overlap = FALSE) +
  labs(x = NULL, y = NULL, fill = "Number of resistant weeds") +
  annotate(geom = "text", x = -40, y = -30, label = "Atlantic ocean", 
           fontface = "italic", color = "blue", size = 4) +
  annotate(geom = "text", x = -80, y = -25, label = "Pacific ocean", 
           fontface = "italic", color = "blue", size = 4) +
  annotation_scale(location = "br", width_hint = 0.4) + 
  annotation_north_arrow(location = "bl", 
                         which_north = "true",
                         pad_x = unit(0.05, "in"), pad_y = unit(0.05, "in"), 
                         style = north_arrow_fancy_orienteering) +
  scale_fill_viridis_c(option = "C", limits = c(0, 54)) -> map2
```


```{r}
label <- glue::glue("**Brazil** has the most cases of herbicide<br> resistant weeds (n={sa_wr$n[1]}), followed by <br>**Argentina** (n={sa_wr$n[2]}), **Chile** (n={sa_wr$n[3]}), <br>**Colombia** (n={sa_wr$n[4]}), **Venezuela** (n={sa_wr$n[5]}), <br>**Bolivia** (n={sa_wr$n[6]}), Paraguay (n={sa_wr$n[7]}), <br>**Uruguay** (n={sa_wr$n[8]}), **Ecuardor** (n={sa_wr$n[9]}),<br> and **Peru** (n={sa_wr$n[10]})")
```


```{r}
map2 + 
  geom_richtext(x = -57, y = -44, 
                hjust = 0, size = 4,
                fill = NA, label.color = NA,
                label = label)
 

ggsave("figure/map.png", width = 9, height = 9)
```



