---
title: "figuras"
author: "Maxwel Coura Oliveira"
date: "6/30/2021"
output: html_document
---


<!-- Figura 1A -->

```{r}
library(tidyverse)
library(pdftools)
library(ggthemes)
library(ggtext)
library(ggtext)
library(extrafont)
library(showtext)
library(dutchmasters)
showtext_auto()
font_add_google("Lato", "lato") 
```



```{r}
raw_pdf <- pdftools::pdf_text("../sindiveg/vendas_hist.pdf")
```


```{r}
raw_text <- raw_pdf[[1]] %>% 
  str_split("\n") %>% 
  unlist()
```

```{r}
table_trimmed <- raw_text %>% 
  .[13:(length(raw_text)-1)] %>% 
  str_trim()
```


```{r}
all_col_names <- c(
  "year",
  "total",
  "herbicida",
  "fungicida",
  "inseticida",
  "acaricida",
  "outros"
)

tab_names <- fwf_empty(
  table_trimmed,
  col_names = all_col_names
)
```

```{r}
vendas_1 <- table_trimmed %>% 
  read_fwf(
    tab_names
  )


vendas_2 <- raw_pdf[[2]] %>% 
  str_split("\n") %>% 
  unlist() %>% 
  .[1:41] %>% 
  str_trim() %>% 
  str_replace_all("\\s{2,}", "|") %>% 
  read_delim(
    delim = "|", 
    col_names = all_col_names
  ) 
```


```{r}
# vendas no valor de US$ 10000
vendas_1 %>% 
  bind_rows(vendas_2) %>% 
  mutate_if(is_character, ~ str_remove_all(., "\\.")) %>% 
   mutate_if(is.double, ~ str_remove_all(., "\\.")) %>% 
  mutate_if(is_character, as.double) %>% 
  filter(!is.na(year)) -> vendas_3
```



Crop harvest - FAO


```{r}
read_csv("../fao/crop_harvest.csv") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(value)) %>% 
  group_by(year) %>% 
  summarise(area = sum(value)) -> area_br
```



# IBGE

```{r eval = FALSE}
readxl::read_excel("../IBGE/area_colhida.xlsx") %>% 
  janitor::row_to_names(row_number = 3) %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  pivot_longer(cols = c("x1974":"x2019"), names_to = "year", values_to = "harvest_ha") %>% 
  rename(location = na) %>% 
  mutate(year = str_remove_all(year, "x")) %>% 
  mutate_at(c("year", "harvest_ha"), as.double)
```



```{r}
vendas_3 %>% 
  left_join(area_br, by = "year") %>% 
  mutate(pesticide = fungicida + inseticida + acaricida) %>% 
  pivot_longer(cols = c(3:6, pesticide), names_to = "type", values_to = "value")  %>%
  mutate(rate_herb = (value * 1000) / area) -> pest_sales
```


```{r}
pest_sales %>% 
  filter(type != "pesticide") %>% 
ggplot(aes(x = year, y = rate_herb, color = type, 
             fill = type, shape = type)) +
  geom_point() +
  geom_line(alpha = 0.5) +
  scale_y_continuous(limits = c(0, 60)) +
  scale_x_continuous(limits = c(1978, 2020), 
                     breaks = seq(1980, 2020, by = 10)) +
  labs(y = expression(paste("Pesticide sales (US$ ha "^"-1",")")),
       x = NULL) +
  scale_color_manual(values = c("grey80", "#d2f8d2", "#FE4E00", "#e5e5ff")) +
  scale_fill_manual(values = c("grey80", "#d2f8d2", "#FE4E00", "#e5e5ff")) +
  scale_shape_manual(values = c(1, 1, 16, 1)) +
  annotate("text", x = 1998, y = 33, 
           fontface = "bold", size = 10,
           label = "Herbicide", color = "#FE4E00") +
  geom_curve(x = 2013, y = 55, 
                   xend = 2011, yend = 57,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = 0.3, color = "#e5e5ff") + 
  annotate("text", x = 2008, y = 57, #fontface = NULL,
           label = "Inseticide", size = 10, color = "#e5e5ff") +
  geom_curve(x = 2007, y = 18, 
                   xend = 2009, yend = 15,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = 0.3, color = "#d2f8d2") + 
  annotate("text", x = 2012, y = 15.5, #fontface = NULL,
           label = "Fungicide", size = 10, color = "#d2f8d2") +
  geom_curve(x = 2011, y = 1.5, 
                   xend = 2013, yend = 5,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = -0.3, color = "grey80") + 
  annotate("text", x = 2016, y = 5, #fontface = NULL,
           label = "Acaricide", size = 10, color = "grey80") +
  geom_smooth(method = "loess", alpha = 0.05) +
  theme_bw(base_family = "lato") +
  theme(plot.title.position = "plot",
        legend.position = "none",
        axis.text = element_markdown(size = 30),
        axis.title = element_markdown(size = 35),
        panel.grid = element_line(color = "gray96")) -> sales
```







```{r}
read_csv("../fao/herbicide_fao.csv")  %>% 
  dplyr::select(Year, Unit, Value) %>% 
  janitor::clean_names() %>% 
  left_join(area_br, by = "year") %>% 
  mutate(rate = (value * 1000) / area) %>% 
  mutate(type =  "herbicide") -> rate_herbicide
```


<!-- Figura 1B -->


# VENDAS DE AGROTÓXICOS E AFINS NO BRASIL NO PERÍODO DE 2000 A 2018 (Unidade: tonelada de ingrediente ativo)


```{r}
path1 <- "../Ibama/ibama_2/Historico total agrotóxicos_por estado_2000_2018-1.xls"


historico <- readxl::read_excel(path1)
```


```{r}
historico1 <- historico %>% 
  janitor::row_to_names(row_number = 2)  %>% 
  janitor::clean_names() %>% 
  rename(location = na) %>% 
  pivot_longer(cols = qtde:var_percent_15, 
               names_to = "variable", values_to = "value") %>% 
  mutate(year = case_when(
    variable %in% c("qtde", "part_percent") ~ "2000",
    variable %in% c("qtde_2", "part_percent_2", "var_percent") ~ "2001",
    variable %in% c("qtde_3", "part_percent_3", "var_percent_2") ~ "2002",
    variable %in% c("qtde_4", "part_percent_4", "var_percent_3") ~ "2003",
    variable %in% c("qtde_5", "part_percent_5", "var_percent_4") ~ "2004",
    variable %in% c("qtde_6", "part_percent_6", "var_percent_5") ~ "2005",
    variable %in% c("qtde_7", "part_percent_7", "var_percent_6") ~ "2006",
    variable %in% c("qtde_8", "part_percent_8", "var_percent_7") ~ "2009",
    variable %in% c("qtde_9", "part_percent_9", "var_percent_8") ~ "2010",
    variable %in% c("qtde_10", "part_percent_10", "var_percent_9") ~ "2011",
    variable %in% c("qtde_11", "part_percent_11", "var_percent_10") ~ "2012",
    variable %in% c("qtde_12", "part_percent_12", "var_percent_11") ~ "2013",
    variable %in% c("qtde_13", "part_percent_13", "var_percent_12") ~ "2014",
    variable %in% c("qtde_14", "part_percent_14", "var_percent_13") ~ "2015",
    variable %in% c("qtde_15", "part_percent_15", "var_percent_14") ~ "2016",
    variable %in% c("qtde_16", "part_percent_16", "var_percent_15") ~ "2017",
    variable %in% c("qtde_17", "part_percent_17", "var_percent_16") ~ "2018",
    TRUE ~ "NA"))
```


```{r}
historico2 <- historico1 %>% 
mutate(variable = str_remove(variable, "(\\s+[A-Za-z]+)?[0-9-]+")) %>% 
  mutate(variable = fct_recode(variable,
                               "qtde" = "qtde_",
                               "part_percent" = "part_percent_",
                               "var_percent" = "var_percent_")) %>% 
  mutate(value = round(as.double(value), 2),
         year = as.integer(year)) %>% 
  group_by(year, location) %>% 
#  rowid_to_column() %>% 
  pivot_wider(
              names_from = variable,  values_fn = list(count=list),
              values_from = value) %>% 
  unchop(everything())
```


```{r}
historico2 %>% 
  filter(location %in% "Total") %>% 
  left_join(area_br, by = c("year")) %>% 
  dplyr::select(year, qtde, area) %>% 
  rename(value = qtde) %>% 
  mutate(rate = value * 1000 / area) %>%
  mutate(type =  "pesticide") -> rate_pesticide
```


```{r}
rate_herbicide %>% 
  bind_rows(rate_pesticide) %>% 
  dplyr::select(-location, -unit) %>% 
  pivot_wider(id_cols = year, names_from = type, values_from = rate) %>% 
  mutate(other = pesticide - herbicide) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "rate") -> ai_rate
```


```{r}
# IBAMA tem dados conjuntos de pesticidas - herbicida separado é apenas na FAO
ai_rate %>% 
  filter(type != "other") %>% 
  filter(!is.na(rate)) %>% 
  ggplot(aes(x = year, y = rate, color = type, 
             fill = type, shape = type)) +
  geom_point() +
  geom_line(alpha = 0.5) +
  geom_smooth(method = "loess", alpha = 0.2) +
  scale_x_continuous(limits = c(1990, 2020), #expand = c(.01, .01),
                     breaks = seq(1990, 2020, by = 5)) +
  scale_y_continuous(limits = c(0, 8), breaks = seq(0, 8, by = 1)) +
  scale_colour_manual(values = c("#FE4E00", "#4B0082")) +
  scale_fill_manual(values = c("#FE4E00", "#4B0082")) +
  scale_shape_manual(values = c(16,1)) +
  annotate("text", x = 2015, y = 2.5, label = "Herbicide", 
           color = "#FE4E00", fontface = "bold", size = 10) +
  annotate("text", x = 2015, y = 6, label = "Pesticides", 
           color = "#4B0082", fontface = "bold", size = 10) +
#  annotate("text", x = 2010, y = 0.1, 
#           label = "Other pesticides: fungicide, insecticide and acaricide", 
#           color = "#4B0082", size = 3) +
  labs(y = expression(paste("Pesticide sales (kg ai ha "^"-1",")")),
       x = NULL, color = NULL, fill = NULL) +
  theme_bw(base_family = "lato") +
  theme(legend.position = "none",
        axis.text = element_markdown(size = 30),
        axis.title = element_markdown(size = 35),
        panel.grid = element_line(color = "gray96")) -> herb
```




```{r}
library(patchwork)
sales | herb

ggsave("Figure 1.png", width = 10, height = 5)
```


<!-- Figura 2 - Aldo -->

```{r message = FALSE}
readxl::read_excel("../Ibama/dados_aldo_2019.xlsx", 
                   sheet = "Var 2009-19 Hs e Culturas") %>% 
  janitor::row_to_names(row_number = 2) %>% 
  slice_head(n = 25) %>%
  mutate(`2008` = as.character(0)) %>% 
  pivot_longer(cols = c(3:13), 
               names_to = "year", 
               values_to = "perc") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(ingrediente_ativo)) %>% 
  rename(ton_ia = x2009) %>% 
  mutate(year = str_replace(year, "2008", "2009")) %>% 
  mutate(ingrediente_ativo = as_factor(ingrediente_ativo)) %>% 
  mutate_if(is_character, as.double) %>%
  mutate_if(is.double, ~round(.,1)) %>% 
  mutate(first_yr = if_else(ingrediente_ativo %in% 
                              c("cletodim", "fenoxaprope-P-etílico",
                                "triclopir-butotílico") , 
                            2010, 
                            2009)) %>% 
  mutate(ton_ia = case_when(
    ingrediente_ativo == "cletodim" ~ 244.5,
    ingrediente_ativo == "fenoxaprope-P-etílico" ~ 55.2,
    ingrediente_ativo == "triclopir-butotílico" ~ 489.8,
    TRUE ~ ton_ia
  )) %>% 
    mutate(perc = case_when(
    ingrediente_ativo == "cletodim" & year == 2009 ~ NA_real_,
    ingrediente_ativo == "fenoxaprope-P-etílico" & year == 2009 ~ NA_real_,
    ingrediente_ativo == "triclopir-butotílico" & year == 2009 ~ NA_real_,
    TRUE ~ perc
  )) %>% 
    mutate(perc = case_when(
    ingrediente_ativo == "cletodim" & year == 2010 ~ 0,
    ingrediente_ativo == "fenoxaprope-P-etílico" & year == 2010 ~ 0,
    ingrediente_ativo == "triclopir-butotílico" & year == 2010 ~ 0,
    TRUE ~ perc
  )) -> perc_increase
```




```{r}
perc_increase %>% 
  mutate(first_yr = case_when(
    ingrediente_ativo %in% c("glufosinato - sal de amônio",
                                "haloxifope-P-metílico",
                                "sulfentrazona") ~ 2017,
    TRUE ~ first_yr
  )) %>% 
    mutate(ton_ia = case_when(
    ingrediente_ativo == "glufosinato - sal de amônio" ~ 1137.65,
    ingrediente_ativo == "haloxifope-P-metílico" ~ 690,
    ingrediente_ativo == "sulfentrazona" ~ 1185.9,
    TRUE ~ ton_ia
  )) %>% 
    mutate(perc = case_when(
    ingrediente_ativo == "glufosinato - sal de amônio" & year == 2009 ~ NA_real_,
    ingrediente_ativo == "haloxifope-P-metílico" & year == 2009 ~ NA_real_,
    ingrediente_ativo == "sulfentrazona" & year == 2009 ~ NA_real_,
    TRUE ~ perc
  )) %>% 
    mutate(perc = case_when(
    ingrediente_ativo == "glufosinato - sal de amônio" & year == 2017 ~ 0,
    ingrediente_ativo == "haloxifope-P-metílico" & year == 2017 ~ 0,
    ingrediente_ativo == "sulfentrazona" & year == 2017 ~ 0,
    TRUE ~ perc)) %>% 
  filter(ingrediente_ativo != "Total") -> perc_increase1
#  mutate(ton_ia = ton_ia / 1000) 
```


```{r}
perc_increase1 %>% 
  mutate(ingrediente_ativo = fct_recode(ingrediente_ativo,
   "2,4-D" = "2,4-d",
   "ametryn" = "ametrina",
   "atrazine" = "atrazina",
   "clethodim" = "cletodim",
   "clomazone" = "clomazona",
   "chlorimurom-ethyl" = "clorimurom-etílico",
   "paraquat" = "dicloreto de paraquate",
   "diuron" = "diurom",
   "fenoxaprop-P" = "fenoxaprope-P-etílico",
   "glyphosate" = "glifosato (soma sais)",
   "glufosinate" = "glufosinato - sal de amônio",
   "haloxifop" = "haloxifope-P-metílico",
   "hexazinone" = "hexazinona",
   "imazaquin" = "imazaquim", 
   "imazethapyr" = "imazetapir",
   "metsulfuron-methyl" = "metsulfurom-metílico",
   "nicosulfuron" = "nicosulfurom",
   "picloram" = "picloram",
   "propanil" = "propanil",
   "simazine" = "simazina",
   "sulfentrazone" = "sulfentrazona",
   "triclopyr" = "triclopir-butotílico",
   "trifluralin" = "trifluralina"
  )) %>% 
  mutate(ingrediente_ativo1 = fct_relevel(ingrediente_ativo,
                                         levels = c("glufosinate", "haloxifop",
                                                    "imazaquin", "nicosulfuron",
                                                    "sulfentrazone", 
                                                    "trifluralin", "glyphosate", 
                                                    "imazethapyr", "clomazone",
                                                    "propanil", "ametryn",
                                                    "atrazine", "hexazinone", "triclopyr",
                                                    "diuron", "fenoxaprop-P",
                                                    "2,4-D","simazine",
                                                    "picloram", "chlorimurom-ethyl", 
                                                    "metsulfuron-methyl", "paraquat", "clethodim"))) %>% 
  mutate(ton_ia = round(ton_ia, 0)) -> perc_increase2
```

```{r}
perc_increase2 %>% 
  mutate(ton_ia2 = paste(ton_ia, "ton ha<sup>-1</sup>")) %>% 
  mutate(ton_ia2009 = if_else(year == 2009 & first_yr == 2009, 
                              ton_ia, NA_real_)) %>% 
  mutate(ton_ia2010 = if_else(year == 2010 & first_yr == 2010, 
                              ton_ia, NA_real_)) %>% 
  mutate(ton_ia2017 = if_else(year == 2017 & first_yr == 2017, 
                              ton_ia, NA_real_)) %>% 
  unite("ton", c(ton_ia2009, ton_ia2010, ton_ia2017), na.rm = TRUE)  -> perc_increase3
```

```{r}
perc_increase3 %>% 
  filter(!is.na(perc)) %>% 
  mutate(group = case_when(
    ingrediente_ativo1 %in% c("glufosinate", "haloxifop", 
                             "imazaquin", "nicosulfuron") ~ "group1",
    ingrediente_ativo1 %in% c("sulfentrazone", "trifluralin", 
                             "glyphosate", "imazethapyr") ~ "group2",
    ingrediente_ativo1 %in% c("clomazone", "propanil", 
                             "ametryn", "atrazine") ~ "group3",
    ingrediente_ativo1 %in% c("hexazinone", "triclopyr", 
                             "diuron", "fenoxaprop-P") ~ "group4",
    ingrediente_ativo1 %in% c("2,4-D", "simazine", 
                             "picloram", "chlorimuron-ethyl") ~ "group5",
    TRUE ~ "group6"
  )) -> perc_increase4
```

```{r}
perc_increase4 %>% 
  mutate(label = case_when(
    ingrediente_ativo1 == "glufosinate" ~ "Values in kg ha<sup>-1</sup> (× 1000)",
    TRUE ~ NA_character_
  )) -> perc_increase5
```


```{r}
perc_increase5 %>% filter(year == 2019) %>% 
  mutate(ton2 = parse_number(ton_ia2)) %>% 
  mutate(ton3 = round(ton2 * (perc/100),0)) %>% 
  mutate(ton4 = ton2 + ton3) -> perc_increase6
```



```{r}
library(ggh4x)
library(lemon)
```


```{r}
perc_increase5 %>% 
  filter(!is.na(perc)) %>% 
  ggplot(aes(x = year, y = perc, color = perc)) +
  geom_line(size = 1) +
  geom_point() +
  scale_x_continuous(limits = c(2008, 2022), 
                     breaks = c(2009, 2012, 2015, 2018, 2021),
                     labels = c("2009", "12", "15", "18", "21")) +
  facet_wrap(~ ingrediente_ativo1,
             ncol = 4, scales = "free_y") +
  facetted_pos_scales(
    y = rep(list(
      scale_y_continuous(limits = c(-80, 60)),
      scale_y_continuous(limits = c(-20, 100)),
      scale_y_continuous(limits = c(-50, 200)),
      scale_y_continuous(limits = c(-40, 350)),
      scale_y_continuous(limits = c(0, 500)),
      scale_y_continuous(limits = c(0, 2300))
    ), each = 4)
  ) +
  scale_color_viridis_c(option = "H",
                        limits = c(-85, 2300)) +
  labs(y = "% active ingrediente increase",
       x = NULL, color = "% increase") +
  theme_bw(base_family = "lato") +
  theme(legend.position = c(0.88, 0.07),
        axis.text = element_markdown(size = 32),
        axis.title = element_markdown(size = 35),
        panel.grid = element_line(color = "gray96"),
        legend.direction = "horizontal",
        legend.key.height = unit(0.7,"cm"),
        legend.key.width = unit(0.9,"cm"),
        legend.key.size = unit(0.2, "cm"),
        legend.title = element_text(face = "bold", size = 30),
        legend.text = element_text(face = "bold", size = 30, 
                                   margin = margin(t = 0.1, 
                                                   b = 0.1, unit = "pt")),
        strip.text.x = element_markdown(face="bold", size = 35) 
        ) +
  guides(colour = guide_colourbar(title.position="top", 
                                  frame.colour = "black",
                                  order = 1)) -> fig1
# facet_wrap2(vars(ingrediente_ativo1), 
 #            scales = "free_y",
 #            ncol = 4, as.table = TRUE,
 #            axes = "full", remove_labels = "all") +
```


```{r warning = FALSE}
fig1 +
  geom_richtext(
    data = perc_increase5 %>% 
                  filter(!is.na(ton)),
    mapping = aes(label = ton), show.legend = FALSE,
    family = "lato",
    fontface = "bold",
    color = "2",
    size = 8,
    fill = NA, 
    label.color = NA,
    hjust = 0
  ) +
    geom_richtext(
    data = perc_increase6,
    mapping = aes(label = ton4), show.legend = FALSE,
    family = "lato",
    fontface = "bold",
    color = "2",
    size = 8,
    fill = NA, 
    label.color = NA,
    hjust = 0
  ) +
   geom_richtext(data = perc_increase5, mapping = aes(x = 2013, y = 50, label = label), 
                 fill = NA, label.color = NA, 
                 fontface = "bold",
                 size = 8, color = 2,
                 inherit.aes = FALSE) 

ggsave("Figure 2.png", height = 12, width = 9)
```








<!-- Figura 3 - Spark -->


```{r}
readxl::read_excel("../spark/spark_1.xlsx", sheet = "spark_1") %>% 
  mutate(perc = perc / 100,
         total_ha_soa = total_ha * perc) %>% 
  mutate(herbicide = str_replace_all(herbicide, "Ohters", "Others")) %>% 
  mutate(mi_ha = round(total_ha / 1000000,1)) %>% 
  mutate(mi_ha = str_glue("{mi_ha} mi")) %>% 
  mutate(herbicide = case_when(
    perc == "0.074" & year == "2015" ~ "FSI",
    TRUE ~ herbicide 
  )) -> soa_total
```


```{r}
soa_total %>% 
  mutate(herbicide = fct_relevel(herbicide,
                                 levels = c("Others", "Glutamina", 
                                            "DPX", "HPPD", "PPO",
                                            "FSI", "ACCase", "ALS",
                                            "FSII", "Auxinas", "EPSPs"))) %>% 
  mutate(percent = scales::percent(perc, accuracy = .1, trim = FALSE)) %>% 
  ggplot(aes(x = season, y = herbicide, 
             label = percent, fill = perc)) +
  geom_tile() +
  scale_fill_viridis_b(option = "H") +
#  coord_flip() +
#  facet_grid(~ season) +
  scale_x_discrete(expand = c(0.01, 0.01), 
                   labels = c("2014/15", "15/16", "16/17", 
                              "17/18", "18/19", "19/20")) +
   geom_text(color = "gray1") +
#  geom_text(soa_total %>% filter(herbicide == "EPSPs"), 
#            mapping = aes(label = mi_ha), y = 0.5, color = "gray30") +
  labs(x = NULL,
       y = NULL,
       fill = NULL) +
  theme_bw(base_family = "lato") +
  theme(legend.position = "none") -> fig_perc


#ggsave("Figure 3.png", width = 5)
```


```{r}
soa_total %>% 
  dplyr::select(season, total) %>% 
  unique() %>% 
  mutate(total_mi = round(total / 1000,2)) -> total_ha 
```

```{r}
total_ha %>% 
  ggplot(aes(x = season, y = total_mi, fill = total_mi)) +
  geom_bar(stat = "identity", show.legend = FALSE, width = 0.8) +
  labs(x = NULL, y = NULL) +
  theme_bw(base_family = "lato") +
  scale_fill_viridis_c(option = "C") +
  geom_text(aes(label = total_mi), nudge_y = -30, fontface = "bold") + 
  annotate("text", x = 1, y = 280, label = "Million ha", fontface = "bold") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank()) -> fig_ha
```


```{r}
library(patchwork)
fig_ha / fig_perc +
  plot_layout(heights = c(1, 3)) 

ggsave("Figure 3.png")
```





```{r}
library(ggbump)
library(cowplot)
library(fishualize)
```

```{r}
soa_total %>% 
  mutate(herbicide = fct_recode(herbicide, 
                                "PSII" = "FSII",
                                "PSI" = "FSI",
                                "DXP" = "DPX",
                                "Auxins" = "Auxinas",
                                "Glutamine" = "Glutamina")) -> soa_total1
```

```{r}
colors <- c("#78A8D1",  "#EFBF6A", "#AF7366", "#CDD4E4",  "#E7CDC2",
            "#CF9FFF", "#B2AAA2", "#B18147", "#C9BDA3", "#FF9999",
            "#a2e665")
```

```{r}
dutchmasters$view_of_Delft
```


```{r}
#library(dutchmasters)
soa_total1 %>% 
  group_by(year) %>% 
  arrange(desc(total_ha_soa)) %>% 
  mutate(rank = row_number()) -> soa_total2

soa_total2 %>% 
  ggplot(aes(x = year, y = rank, color = herbicide,
             label = herbicide)) +
  geom_text(data = soa_total2 %>% filter(year == 2020),
            mapping = aes(x = year + .3, label = herbicide), 
            size = 11, hjust = 0, fontface = "bold") +
  geom_text(data = soa_total2 %>% filter(year == 2015),
            mapping = aes(x = year - .3, label = herbicide), 
            size = 11, hjust = 1, fontface = "bold") +
  geom_text(data = soa_total2,
            mapping = aes(y = 12, label = mi_ha), 
            size = 9, hjust = 0.5, color = "#333333", fontface = "italic") +
  geom_text(data = soa_total2 %>% filter(year == 2015),
            mapping = aes(y = rank, x = year - 1.2, label = rank), 
            size = 9, hjust = 0.5, color = "#333333", fontface = "bold") +
  geom_segment(aes(x = 2013.8, y = 11.6, 
                   xend = 2020.8, yend = 11.6),
               color = 1) +
  geom_segment(aes(x = 2013.8, y = 12.4, 
                   xend = 2020.8, yend = 12.4),
               color = "#333333") +
  annotate("text", x = 2014.2, y = 12, color = "#333333", size = 10, 
           label = "Total ha", fontface = "italic") +
  geom_point(size = 8) +
  geom_bump(size = 2, smooth = 8) +
  geom_text(data = soa_total2 ,
            mapping = aes(label = perc*100), 
            size = 10, color = "#333333") +
  scale_x_continuous(limits = c(2013.8, 2020.8),
                     breaks = seq(2015, 2020, 1),
                     labels = c("2014/15", "15/16", "16/17", 
                              "17/18", "18/19", "19/20")) +
  theme_minimal(base_family = "lato") +
  scale_y_reverse(breaks = seq(0, 12, 1)) +
  scale_color_manual(values = colors) +
#  scale_color_brewer(palette = "Paired") +
#  scale_color_dutchmasters(palette = "little_street") +
  labs(x = NULL, y = NULL) +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_markdown(size = 30, face = "bold", 
                                       vjust = 0.5, margin = margin(-0.3,0,0,0, 
                                                                    unit = 'cm')),
        panel.grid = element_blank())

ggsave("Figure 3.png", bg = "gray96")
```




```{r}
readxl::read_excel("../spark/spark_3.xlsx", sheet = "spark_2") %>% 
  mutate(perc_soa = perc_soa / 100,
         perc_crop = perc_crop / 100,
         total_ha_soa = total_ha_season * perc_soa * perc_crop) %>% 
  mutate(crop = str_to_title(crop)) %>% 
  mutate(mi_ha = round(total_ha_soa / 1000000, 5),
         mi_ha = str_glue("{mi_ha} mi ha")) %>% 
  mutate(soa = fct_recode(soa,
                          "PSI" = "FSI",
                          "Glutamine" = "Glutamina",
                          "VLCFA" = "Divisao celular",
                          "Auxins" = "Auxinas",
                          "PSII" = "FSII")) -> soa_crop
```

```{r}
soa_crop 
```




```{r}
library(hrbrthemes)
options(scipen=999)
soa_crop %>%  
#  filter(crop == "Soybean") %>% 
  ggplot(aes(x = year, y = total_ha_soa/1000000, fill = soa)) +
  geom_area() +
  facet_wrap(~ crop, scales = "free") +
#  coord_flip() +
  labs(x = NULL,
       y = "Million ha",
       fill = "Herbicide sites of action") +
#  scale_fill_ipsum() +
   scale_fill_brewer(palette = "Paired") +
#  scale_fill_viridis_d(option = "F", guide = guide_legend(nrow = 2)) +
  scale_x_continuous(breaks = c(2018, 2019, 2020), 
                     labels = c("2017/18", "18/19", "19/20")) +
  theme_bw(base_family = "lato") +
  theme(legend.position = c(0.85, 0.25),
        legend.text = element_markdown(size = 9),
        legend.key.size = unit(1,"line"),
        strip.text = element_markdown(face = "bold", size = 10)) +
  guides(fill = guide_legend(nrow = 6))

ggsave("Figure 4A.png", dpi = 300)
```

```{r}
soa_crop %>%
  mutate(soa_mi = round(total_ha_soa/1000000,1)) %>% 
  filter(soa_mi > 0) %>% 
  mutate(soa = fct_relevel(soa, levels = c("Others", "DPX", "Glutamine",
                                           "PSI", "VLCFA", "HPPD", "ACCase",
                                           "PPO", "ALS", "Auxins", "PSII",
                                           "EPSPs"))) %>% 
  ungroup() %>% 
  mutate(crop = fct_relevel(crop, levels = c("Soybean", "Pasture", "Corn",
                                             "Sugarcane", "Cotton"))) %>% 
  mutate(year_season = case_when(
    year_season == "17/18" ~ "2017/18",
    year_season == "18/19" ~ "2018/19",
    TRUE ~  "2019/20")) |> 
  mutate(crop_area = round(crop_area, 1)) -> soa_crop1
```


```{r}
library(ggh4x)
soa_crop1 %>% 
  ggplot(aes(x = soa, y = soa_mi, 
             fill = year_season)) +
  geom_bar(stat = "identity",
           position = position_dodge2(width = 1, reverse = FALSE)) +
  facet_grid(~ crop, scales = "free") +
  facetted_pos_scales(
    y = rep(list(
      scale_y_continuous(limits = c(0, 100)),
      scale_y_continuous(limits = c(0, 5)),
      scale_y_continuous(limits = c(0, 5)),
      scale_y_continuous(limits = c(0, 2.5)),
      scale_y_continuous(limits = c(0, 0.5))
    ), each = 1)
  ) +
  coord_flip() +
#  scale_fill_dutchmasters(palette = "pearl_earring",
#                           guide = guide_legend(reverse = TRUE)) +
  scale_fill_colorblind(labels = c("2017/18", "18/19", "19/20")) +
  geom_text(data = soa_crop1, mapping = aes(x = soa, y = soa_mi,
                label = soa_mi), size = 5, hjust = -0.2,
            position = position_dodge2(width = 1, reverse = FALSE)) +
#  scale_y_continuous(limits = c(0, 155)) +
  labs(x = NULL,
       y = "Million ha",
       fill = NULL) +
  theme_bw(base_family = "lato") +
  theme(legend.position = c(0.3,0.2),
        legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        legend.key.size = unit(0.7, "lines"),
        legend.title = element_markdown(size = 20, face = "bold", 
                                        lineheight = 0.2),
        legend.text = element_markdown(size = 22),
        axis.title = element_markdown(size = 30),
        axis.text = element_markdown(size = 25),
        strip.text = element_markdown(face = "bold", size = 26)) +
  guides(fill = guide_legend(nrow = 3, reverse = TRUE)) -> fig4a

ggsave("Figure 4B.png", height = 4, width = 8, dpi = 300)
```


```{r}
library(gtExtras)
library(gt)
```


```{r}
soa_crop1 |> 
  dplyr::select(crop, crop_area, soa, year_season, soa_mi) |> 
  pivot_wider(id_cols = c(crop, year_season, crop_area),
              names_from = soa, values_from = soa_mi) |> 
  rename(season = year_season) |> 
  dplyr::select(crop, season, crop_area, ACCase, Auxins, ALS, DPX, EPSPs,
                Glutamine, HPPD, PPO, PSI, PSII, VLCFA, Others) |> 
  mutate(Total = rowSums(across(where(is.numeric)), na.rm = TRUE) - crop_area) |> 
  mutate(season = fct_recode(season,
                             "18/19" = "2018/19",
                             "19/20" = "2019/20")) |> 
#  mutate_if(is.double, ~replace_na(., 0)) |> 
  rename(`Crop area` = crop_area,
         `Total SOA` = Total) |> 
  gt(groupname_col = "crop") |> 
  gt_theme_538() |> 
  tab_footnote(
    footnote = "Source: Conab and IBGE",
    locations = cells_column_labels(
      columns = `Crop area`
    )) |> 
  tab_footnote(
    footnote = "gray cells means no data available",
    locations = cells_column_labels(
      columns = c(4,6:15)
    )) |> 
  gt_hulk_col_numeric(4:16, trim = TRUE) |> 
  fmt_missing(3:16, missing_text = "") |> 
  tab_spanner(
    label = "Herbicide Sites of Action",
    columns = c(4:15)) |> 
  tab_spanner(
    label = "Million ha",
    columns = c(3:16)) -> table

gtsave(table, "table.png")
```




```{r}
# pat * 1000
readxl::read_excel("../spark/spark_1.xlsx", sheet = "spark_3") %>% 
  mutate(crop = str_to_title(crop)) %>% 
  mutate(pat = pat / 1000) %>% 
  ungroup() %>% 
  mutate(crop = fct_relevel(crop, levels = c("Other Crops", "Cotton", "Pasture",   
                                              "Sugarcane", "Corn", "Soybean"))) -> crop_soa3
```



```{r}
crop_soa3  %>% 
  ggplot(aes(x = factor(year), y = pat, fill = crop)) +
   geom_bar(stat = "identity", width = 0.4,
           position = position_stack()) +
  scale_fill_calc() +
  labs(x = NULL, y = "Million ha") +
  geom_text(aes(label = round(pat,0)), 
            position = position_stack(vjust = 0.5), 
            fontface = "bold", size = 9) +
  scale_x_discrete(expand = c(0.1, 0.1),
                   labels = c("2017/18", "18/19", "19/20")) +
  coord_flip() +
  annotate("text", x = 1.7, y = 20, size = 10, label = "Soybean", 
           color = "#83caff", fontface = "bold") +
  geom_curve(x = 2, y = 50, 
                   xend = 1.7, yend = 44,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = -0.3, color = "#83caff") + 
  annotate("text", x = 2.31, y = 170, size = 10, label = "Corn",
           color = "#7e0021", fontface = "bold") +
  geom_curve(x = 2.1, y = 175, 
                   xend = 2.27, yend = 170,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = -0.3, color = "#7e0021") + 
  annotate("text", x = 1.7, y = 197, size = 10, label = "Sugarcane",
           color = "#579d1c", fontface = "bold") +
  geom_curve(x = 2, y = 210, 
                   xend = 1.73, yend = 200,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = -0.3, color = "#579d1c") + 
  annotate("text", x = 2.31, y = 240, size = 10, label = "Pasture",
           color = "#ffd320", fontface = "bold") +
  geom_curve(x = 2.1, y = 235, 
                   xend = 2.27, yend = 240,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = -0.3, color = "#ffd320") + 
  annotate("text", x = 1.7, y = 258, size = 10, label = "Cotton",
           color = "#ff420e", fontface = "bold") +
  geom_curve(x = 1.9, y = 255, 
                   xend = 1.73, yend = 253,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = 0.3, color = "#ff420e") + 
  annotate("text", x = 2.31, y = 293, size = 10, label = "Other crops",
           color = "#004586", fontface = "bold") +
  geom_curve(x = 2.1, y = 280, 
                   xend = 2.27, yend = 293,
               arrow = arrow(length = unit(0.07, "inch")), 
               size = 0.4, curvature = 0.3, color = "#004586") + 
  theme_bw(base_family = "lato") +
  theme(legend.position = "none",
        legend.title = element_blank(),
        legend.text = element_markdown(size = 25),
        legend.direction = "horizontal",
        axis.text.y = element_markdown(size = 30),
        axis.text.x = element_markdown(size = 30),
        axis.title = element_markdown(size = 35)) +
  guides(fill = guide_legend(nrow = 2))

ggsave("Figure 4A.png", width = 5, height = 5)
```
```{r}
library(scales)
show_col(calc_pal()(6))
```










