---
title: "argentina"
author: "Maxwel Coura Oliveira"
date: "10/15/2021"
output: html_document
---

```{r}
library(gtExtras)
library(gt)
library(tidyverse)
library(ggfittext)
```


```{r}
readxl::read_excel("argentina_2.xlsx", sheet = "herbicide") |> 
  mutate(`Treated ha` =  round(`Treated ha` / 1000000, 2)) |> 
  mutate(`Harvested ha` = round(`Harvested ha` / 1000000,2)) |> 
  mutate(`% of treated` = round((`Treated ha` / `Harvested ha`) * 100,1)) |> 
  rename(`Treated` = `Treated ha` , 
         `Harvested` = `Harvested ha`) |> 
  arrange(Crop) -> ar_table
```

```{r}
ar_table |> 
  gt() |> 
  gt_theme_538() |> 
  tab_footnote(
    footnote = "Marsico 1980",
    locations = cells_column_labels(
      columns = 1
    )) |> 
  tab_footnote(
    footnote = "Data from MAGyP",
    locations = cells_column_labels(
      columns = 3
    )) |> 
  tab_spanner(
    label = "Area (million ha)",
    columns = c(2,3)) -> table1


gtsave(table1, "table1.png")
```



```{r}
readxl::read_excel("argentina_2.xlsx", sheet = "soa") -> ar_table2
```




```{r}
ar_table2 |> 
  gt() |> 
  gt_theme_538() |> 
  fmt_missing(everything(), missing_text = "") -> table2

gtsave(table2, "table2.png")
```


```{r}
tribble(
  ~herbicide, ~year, ~value,
  "Glyphosate", 2008, 1426,
  "Glyphosate", 2013, 1051,
  "Glyphosate", 2014, 1132,
  "Glyphosate", 2015, 860,
  "Glyphosate", 2016, 741,
  "Glyphosate", 2017, 612,
  "Glyphosate", 2018, 615,
  "Glyphosate", 2019, 709,
  "Other herbicides", 2008, 351,
  "Other herbicides", 2013, 757,
  "Other herbicides", 2014, 967,
  "Other herbicides", 2015, 916,
  "Other herbicides", 2016, 1014,
  "Other herbicides", 2017, 1142,
  "Other herbicides", 2018, 1196,
  "Other herbicides", 2019, 1255
) -> fig5
```


```{r}
fig5 |> 
  ggplot(aes(x = factor(year), y = value, 
             fill = herbicide, label = value)) +
  geom_bar(stat = "identity", position = "stack") +
  theme_bw(base_family = "lato") +
  labs(x = NULL, y = "Herbicide sales (Million US$)", fill = NULL, 
       caption = "**Source:** BASF, Corteva, and Syngenta") +
  theme(legend.position = "bottom") +
  scale_fill_colorblind() +
  geom_bar_text(position = "stack", reflow = TRUE, size = 25) +
  theme(legend.position = "bottom",
        legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        legend.key.size = unit(0.7, "lines"),
        legend.title = element_markdown(size = 20, face = "bold", 
                                        lineheight = 0.2),
        legend.text = element_markdown(size = 22),
        axis.title = element_markdown(size = 30),
        plot.caption = element_markdown(size = 20, color = "#333333"),
        axis.text = element_markdown(size = 25),
        strip.text = element_markdown(face = "bold", size = 26))

ggsave("figure5.png", width = 6, height = 4)
```



```{r}
tribble(
  ~year, ~volume, ~price, ~type,
  1990, 0.380, 5, "A",
  1995, 0.990, 12, "A",
  1996, 1.291, 17, "A",
  1997, 1.646, 21, "A",
  1998, 2.058, 24, "A",
  1999, 2.090, 23, "A",
  2000, 2.080, 18, "A",
  2005, 6.726, 37, "A",
  2007, 10.991, 68, "A",
  2014, 19.058, 155, "A",
  2018, 12.488, 107, "A",
  2020, 10.391, 77, "A"
) -> fig6
```


```{r}
ylim.prim <- c(0, 179)   # in this example, precipitation
ylim.sec <- c(0, 22)    # in this example, temperature
b <- diff(ylim.prim)/diff(ylim.sec)
a <- ylim.prim[1] - b*ylim.sec[1] # there was a bug here
```



```{r}
fig6 |> 
  ggplot(aes(x = factor(year), y = a + volume*b)) +
  geom_bar(stat = "identity", fill = "#E69F00", show.legend = TRUE) +
  labs(x = NULL) +
  scale_y_continuous(
    "Volume (× 1000 ton of active ingredient)", 
        sec.axis = sec_axis(~ (. - a)/b, name = "CIF price (million US$)",
                        breaks = seq(0, 22, 5))) +
  geom_point(aes(x = factor(year), y = price),
             size = 3,
             shape = 23,
             fill = 1) +
  geom_line(aes(x = factor(year), 
                y = price, 
                group = type),
            show.legend = TRUE,
            color = 1) +
  theme_bw(base_family = "lato") +
  annotate("richtext", label = "CIF price",
           size = 10,
           fill = "#E69F00",
           fontface = "bold",
           color = 1,
           x = 7.6, y = 70) +
  annotate("text", label = "Volume",
           fontface = "bold",
           size = 10,
           color = 1,
           x = 4, y = 30) +
  theme(legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        legend.key.size = unit(0.7, "lines"),
        legend.text = element_markdown(size = 22),
        axis.title = element_markdown(size = 30),
        axis.text = element_markdown(size = 25),
        strip.text = element_markdown(face = "bold", size = 26)) -> fig6a

ggsave("fig6.png")
```

