---
title: "sindiveg"
author: "Maxwel Coura Oliveira"
date: "5/6/2021"
output: html_document
---



```{r} 
library(tidyverse)
```

```{r warning = FALSE, message = FALSE}
# qde produto comercial (ton)
prod_comercial1 <- readxl::read_excel("Sindiveg Pesticide data 2000-2009.xls") %>% 
  janitor::row_to_names(row_number = 7) %>% 
  janitor::clean_names() %>% 
  rename(cultura = na) %>%
  dplyr::select(1:11) %>% 
  mutate(x2000 = as.double(x2000)) %>%
  pivot_longer(cols = 2:11, 
               names_to = "ano", 
               values_to = "ton_prod") %>% 
  filter(cultura != "Total Geral:") %>% 
  mutate(ano = str_remove(ano, pattern = "x")) %>% 
  drop_na()
glimpse(prod_comercial1)
```

```{r}
# produto comercial apenas
readxl::read_excel("Sindiveg Pesticide data 2010 - 12.xls") %>% 
  janitor::row_to_names(row_number = 5) %>% 
  janitor::clean_names() %>% 
  rename(cultura = na) %>%
  dplyr::select(1:4) %>% 
  mutate(x2010 = as.double(x2010)) %>%
  pivot_longer(cols = 2:4, 
               names_to = "ano", 
               values_to = "ton_prod") %>% 
  filter(cultura != "Total Geral:") %>% 
  mutate(ano = str_remove(ano, pattern = "x")) %>% 
  drop_na()
glimpse(prod_comercial) -> prod_comercial2 
```

```{r}
prod_comercial1 %>% 
  bind_rows(prod_comercial2) -> prod_comercial
```


```{r warning = FALSE, message = FALSE}
# qde ingrediente ativo (ton)
ing_ativo1 <- readxl::read_excel("Sindiveg Pesticide data 2000-2009.xls") %>% 
  janitor::row_to_names(row_number = 7) %>% 
  janitor::clean_names() %>% 
  rename(cultura = na) %>%
  dplyr::select(1, 12:21) %>% 
  mutate(x2000_2 = as.double(x2000_2)) %>% 
    pivot_longer(cols = 2:11, 
               names_to = "ano", 
               values_to = "ton_ing") %>% 
  filter(cultura != "Total Geral:") %>% 
  mutate(ano = str_remove(ano, pattern = "x"),
         ano = str_remove(ano, pattern = "_2")) %>% 
  drop_na()
glimpse(ing_ativo1)
```

```{r}
# produto comercial apenas
readxl::read_excel("Sindiveg Pesticide data 2010 - 12.xls") %>% 
  janitor::row_to_names(row_number = 5) %>% 
  janitor::clean_names() %>% 
  rename(cultura = na) %>%
  dplyr::select(1, 5:7) %>% 
  mutate(x2010_2 = as.double(x2010_2)) %>% 
    pivot_longer(cols = 2:4, 
               names_to = "ano", 
               values_to = "ton_ing") %>% 
  filter(cultura != "Total Geral:") %>% 
  mutate(ano = str_remove(ano, pattern = "x"),
         ano = str_remove(ano, pattern = "_2")) %>% 
  drop_na() -> ing_ativo2
```


```{r}
ing_ativo1 %>% 
  bind_rows(ing_ativo2) -> ing_ativo
```



```{r warning = FALSE, message = FALSE}
# valor (US$ 1000)
valor1 <- total <- readxl::read_excel("Sindiveg Pesticide data 2000-2009.xls") %>% 
  janitor::row_to_names(row_number = 7) %>% 
  janitor::clean_names() %>% 
  rename(cultura = na) %>%
  dplyr::select(1, 22:31) %>% 
  mutate(x2000_3 = as.double(x2000_3)) %>% 
    pivot_longer(cols = 2:11, 
               names_to = "ano", 
               values_to = "valor_mil_us") %>% 
  filter(cultura != "Total Geral:") %>% 
  mutate(ano = str_remove(ano, pattern = "x"),
         ano = str_remove(ano, pattern = "_3")) %>% 
  drop_na()
```


```{r}
# produto comercial apenas
readxl::read_excel("Sindiveg Pesticide data 2010 - 12.xls") %>% 
  janitor::row_to_names(row_number = 5) %>% 
  janitor::clean_names() %>% 
  rename(cultura = na) %>%
  dplyr::select(1, 8:31) %>% 
  mutate(x2000_3 = as.double(x2000_3)) %>% 
    pivot_longer(cols = 2:11, 
               names_to = "ano", 
               values_to = "valor_mil_us") %>% 
  filter(cultura != "Total Geral:") %>% 
  mutate(ano = str_remove(ano, pattern = "x"),
         ano = str_remove(ano, pattern = "_3")) %>% 
  drop_na()
glimpse(valor)
```


```{r}
sindveg_pest <- prod_comercial1 %>% 
  left_join(ing_ativo1, by = c("cultura", "ano")) %>% 
  left_join(valor1, by = c("cultura", "ano")) %>% 
  drop_na() %>% 
  mutate(ano = as.double(ano))
```


```{r}
readxl::read_excel("Sindiveg Pesticide data 2010 - 12.xls") %>% 
  janitor::row_to_names(row_number = 5) %>% 
  janitor::clean_names() %>% 
  rename(cultura = na) %>%
  dplyr::select(1:4) %>% 
  mutate(x2010 = as.double(x2010)) %>%
  pivot_longer(cols = 2:4, 
               names_to = "ano", 
               values_to = "ton_prod") %>% 
  filter(cultura != "Total Geral:") %>% 
  mutate(ano = str_remove(ano, pattern = "x")) %>% 
  drop_na()
glimpse(prod_comercial)
```




```{r}
sindveg_pest %>% 
  filter(cultura %in% c("Soybean", "Café")) %>% 
  ggplot(aes(x = ano, y = ton_ing, color = cultura)) +
  geom_line() +
  geom_point() +
  ggsave("soja.png")
```


----

Conab

```{r}
readxl::read_excel("conab/soja.xls", sheet = "Área") %>% 
  janitor::row_to_names(row_number = 4) %>% 
  filter(!is.na(`1976/77`)) %>% 
  rename(location = `REGIÃO/UF`) %>% 
  mutate(location = as_factor(location)) %>% 
  mutate_if(is_character, as.double) %>% 
  pivot_longer(cols = 2:46, names_to = "year", values_to = "area") %>% 
  mutate(year = str_remove_all(year, "/[^/]*$"),
         year = as.double(year) + 1) %>% 
  filter(location == "BRASIL") -> brasil
```


```{r}
sindveg_pest %>% 
  filter(cultura == "Soybean") %>% 
  left_join(brasil, by = c("ano" = "year")) %>% 
  mutate(area = area * 1000) %>% 
  mutate(rate = ton_ing *1000 / area) %>% 
  ggplot(aes(x = ano, y = rate)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = seq(2000, 2009, 1)) +
  ylim(0, 5) +
  labs(y = "Ingrediente ativo (kg/ha)",x = NULL) +
  theme_linedraw()
```

```{r}
readxl::read_excel("conab/algodao.xls", sheet = "Área") %>% 
  janitor::row_to_names(row_number = 4) %>% 
  filter(!is.na(`1976/77`)) %>% 
  rename(location = `REGIÃO/UF`) %>% 
  mutate(location = as_factor(location)) %>% 
  mutate_if(is_character, as.double) %>% 
  pivot_longer(cols = 2:46, names_to = "year", values_to = "area") %>% 
  mutate(year = str_remove_all(year, "/[^/]*$"),
         year = as.double(year) + 1) %>% 
  filter(location == "BRASIL") -> algodao
```

```{r}
sindveg_pest %>% 
  filter(cultura == "Algodão") %>% 
  left_join(brasil_arroz, by = c("ano" = "year")) %>% 
  mutate(area = area * 1000) %>% 
  mutate(rate = ton_ing *1000 / area) %>% 
  ggplot(aes(x = ano, y = rate)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = seq(2000, 2009, 1)) +
  ylim(0, 5) +
  labs(y = "Ingrediente ativo (kg/ha)",x = NULL) +
  theme_linedraw()
```