---
title: "paraguai"
author: "Maxwel Coura Oliveira"
date: "8/19/2021"
output: html_document
---

```{r}
library(tidyverse)
library(ggthemes)
library(ggtext)
library(extrafont)
library(showtext)
showtext_auto()
font_add_google("Lato", "lato") 
```


```{r}
options(scipen = 999)
readxl::read_excel("herbicidas_paraguai.xlsx", sheet = "Resumo Final") %>% 
  janitor::clean_names() %>% 
  dplyr::select(1:4) %>% 
  pivot_longer(c(`x2018_kg_ia`, `x2019_kg_ia`, `x2020_kg_ia`), 
               names_to = "year", values_to = "value") %>% 
  mutate(year = extract_numeric(year)) %>% 
  mutate(producto = str_to_lower(producto)) %>% 
  mutate(year = as.double(year)) %>% 
  mutate_if(is.double, ~round(., 1)) -> py
```

```{r}
py %>% 
  filter(!producto %in% c("total general", "dimetilamina", "outros")) %>% 
  mutate(producto = fct_relevel(producto,
                                levels = c("fluroxipir", "flumioxazin", "diclosulam",
                                           "dicamba", "imazetapyr", "picloram",
                                           "simazina","fomesafen", "diuron",
                                           "haloxifop-p- metil", "atrazina", "triclopir",
                                           "glufosinato", "cletodim", "paraquat", 
                                           "2,4-d", "glifosato"))) -> py1
```

```{r}
py1 %>% 
  mutate(producto = fct_recode(producto,
                               "glyphosate" = "glifosato",
                               "paraquat" = "paraquat",
                               "2,4-D" = "2,4-d",
                               "clethodim" = "cletodim",
                               "glufosinate" = "glufosinato",
                               "triclopyr" = "triclopir",
                               "haloxyfop" = "haloxifop-p- metil",
                               "diuron" = "diuron",
                               "fomesafen" = "fomesafen",
                               "atrazine" = "atrazina",
                               "simazine" = "simazina",
                               "picloram" = "picloram", 
                               "imazethapyr" = "imazetapyr",
                               "dicamba" = "dicamba",
                               "diclosulam" = "diclosulam", 
                               "flumioxazin" = "flumioxazin", 
                               "fluroxypyr" = "fluroxipir")) -> py2
```


```{r}
py2 %>% 
#  filter(producto != "total general") %>% 
  ggplot(aes(x = year, y = value/1000, fill = producto)) +
  geom_bar(stat = "identity", width = 0.5,
           position = position_dodge2(width = 0.4)) +
  facet_wrap(~ producto, nrow = 5, scales = "free") +
#  coord_flip() +
  scale_fill_viridis_d(option = "E") +
  scale_x_continuous(breaks = seq(2018, 2020, by = 1)) +
  geom_text(aes(label = round(value/1000,0)), size = 9, 
            position = position_nudge(y = 0), color = 2, fontface = "bold") +
  labs(x = NULL,
       y = "Active ingredient (kg × 1000)") +
  theme_bw(base_family = "lato") +
  theme(legend.position = "none",
        axis.title = element_markdown(size = 35),
        axis.text = element_markdown(size = 32),
        strip.text = element_markdown(size = 35, face = "bold"))

ggsave("py.png", height = 10)
```


```{r}
py2 |> 
  ggplot(aes(x = producto, y = value/1000, fill = as_factor(year))) +
  geom_bar(stat = "identity", position = position_dodge2(width = 1,
                                                        preserve = "total",
                                                        #reverse = TRUE,
                                                        padding = 0.2)) +
  coord_flip() +
  geom_text(aes(label = round(value/1000,0), color = as_factor(year)), size = 12, 
            position = position_dodge(width = 1), 
            hjust = -0.2, fontface = "bold", show.legend = FALSE) +
  ylim(0, 5000) +
  labs(x = NULL,
       y = "kg of active ingredient (× 1000)",
       caption = "**Source:** INBIO, 2021") +
  scale_fill_colorblind(guide = guide_legend(reverse = TRUE)) +
  scale_color_colorblind() +
  theme_bw() +
  theme(legend.position = c(0.9, 0.5),
        legend.title = element_blank(),
        legend.text = element_text(size = 40),
        legend.background = element_blank(),
        axis.title = element_markdown(size = 47),
        plot.caption = element_markdown(size = 25, color = "#333333"),
        axis.text = element_markdown(size = 47))

ggsave("py2.png", height = 12)
```


